// 英検1級パス単 よく出る重要単語 Section 1〜7（0001-0700）全700語
// PDFより抽出（でる順 A）
// Section 1〜3: 英検1級パス単A1_3.pdf
// Section 4〜7: 英検1級パス単A4_7.pdf

const EIKEN1_WORDS = [
// Section 1 (0001-0100)
  { id:"0001", word:"claim", phonetic:"kleɪm", pos:"動詞", meaning:"を主張する", note:"名 主張", section:1 },
  { id:"0002", word:"project", phonetic:"prəˈdʒekt", pos:"動詞", meaning:"を見積もる、を提示する", note:"projection 名 予測", section:1 },
  { id:"0003", word:"expand", phonetic:"ɪkˈspænd", pos:"動詞", meaning:"拡大する", note:"expansion 名; expansive 形", section:1 },
  { id:"0004", word:"address", phonetic:"əˈdres", pos:"動詞", meaning:"に対応する、に取り組む", note:"名 演説; ≒ cope with, tackle", section:1 },
  { id:"0005", word:"detect", phonetic:"dɪˈtekt", pos:"動詞", meaning:"を感知する、を発見する", note:"detective 形; detection 名", section:1 },
  { id:"0006", word:"evolve", phonetic:"ɪˈvɒlv", pos:"動詞", meaning:"進化する", note:"≒ develop; evolution 名", section:1 },
  { id:"0007", word:"guarantee", phonetic:"ˌɡærənˈtiː", pos:"動詞", meaning:"を保証する", note:"名 保証", section:1 },
  { id:"0008", word:"implement", phonetic:"ˈɪmplɪment", pos:"動詞", meaning:"を実行する", note:"≒ carry out, execute; implementation 名", section:1 },
  { id:"0009", word:"weather", phonetic:"ˈweðər", pos:"動詞", meaning:"を切り通す、をしのぐ", note:"≒ survive", section:1 },
  { id:"0010", word:"justify", phonetic:"ˈdʒʌstɪfaɪ", pos:"動詞", meaning:"を正当化する", note:"justification 名; justifiable 形", section:1 },
  { id:"0011", word:"convict", phonetic:"kənˈvɪkt", pos:"動詞", meaning:"に有罪判決を下す（of ~について）", note:"≒ pronounce guilty", section:1 },
  { id:"0012", word:"prioritize", phonetic:"praɪˈɒrɪtaɪz", pos:"動詞", meaning:"を優先させる", note:"prioritization 名", section:1 },
  { id:"0013", word:"rebel", phonetic:"rɪˈbel", pos:"動詞", meaning:"反抗する（against ~に）", note:"rebellion 名; rebellious 形", section:1 },
  { id:"0014", word:"fuel", phonetic:"fjuːəl", pos:"動詞", meaning:"を悪化させる、に燃料を供給する", note:"名 燃料", section:1 },
  { id:"0015", word:"sustain", phonetic:"səˈsteɪn", pos:"動詞", meaning:"を維持する、に耐える", note:"sustainable 形; sustenance 名", section:1 },
  { id:"0016", word:"portray", phonetic:"pɔːrˈtreɪ", pos:"動詞", meaning:"を描写する", note:"≒ describe, depict; portrait 名 肖像", section:1 },
  { id:"0017", word:"manipulate", phonetic:"məˈnɪpjʊleɪt", pos:"動詞", meaning:"を巧みに操る", note:"manipulation 名", section:1 },
  { id:"0018", word:"stimulate", phonetic:"ˈstɪmjʊleɪt", pos:"動詞", meaning:"を刺激する", note:"stimulation 名; stimulus 名", section:1 },
  { id:"0019", word:"integrate", phonetic:"ˈɪntɪɡreɪt", pos:"動詞", meaning:"を統合する", note:"integration 名; ⇔ segregate", section:1 },
  { id:"0020", word:"undergo", phonetic:"ˌʌndərˈɡoʊ", pos:"動詞", meaning:"（検査・治療）を受ける", note:"≒ experience, go through", section:1 },
  { id:"0021", word:"diagnose", phonetic:"ˈdaɪəɡnoʊz", pos:"動詞", meaning:"を診断する", note:"diagnosis 名", section:1 },
  { id:"0022", word:"enforce", phonetic:"ɪnˈfɔːrs", pos:"動詞", meaning:"（法律など）を施行する", note:"enforcement 名", section:1 },
  { id:"0023", word:"abuse", phonetic:"əˈbjuːz", pos:"動詞", meaning:"を悪用する、を虐待する", note:"≒ misuse; abuse drugs 薬物を乱用する", section:1 },
  { id:"0024", word:"dismiss", phonetic:"dɪsˈmɪs", pos:"動詞", meaning:"を却下する、を解雇する", note:"≒ reject; ≒ fire; dismissal 名", section:1 },
  { id:"0025", word:"migrate", phonetic:"ˈmaɪɡreɪt", pos:"動詞", meaning:"移住する", note:"migration 名; migrant 名 移住者", section:1 },
  { id:"0026", word:"contradict", phonetic:"ˌkɒntrəˈdɪkt", pos:"動詞", meaning:"に反論する、と矛盾する", note:"contradiction 名", section:1 },
  { id:"0027", word:"plague", phonetic:"pleɪɡ", pos:"動詞", meaning:"を悩み苦しめる（with ~で）", note:"名 疫病", section:1 },
  { id:"0028", word:"complex", phonetic:"ˈkɒmpleks", pos:"名詞", meaning:"複合施設", note:"apartment complex 集合住宅", section:1 },
  { id:"0029", word:"congress", phonetic:"ˈkɒŋɡres", pos:"名詞", meaning:"（Congress）米国議会", note:"congressional 形", section:1 },
  { id:"0030", word:"antibiotic", phonetic:"ˌæntɪbaɪˈɒtɪk", pos:"名詞", meaning:"抗生物質", note:"", section:1 },
  { id:"0031", word:"amendment", phonetic:"əˈmendmənt", pos:"名詞", meaning:"修正、改正、修正案", note:"amend 動; constitutional amendment 憲法修正", section:1 },
  { id:"0032", word:"plot", phonetic:"plɒt", pos:"名詞", meaning:"陰謀、策略", note:"≒ conspiracy; ≒ scheme", section:1 },
  { id:"0033", word:"advocate", phonetic:"ˈædvəkeɪt", pos:"名詞", meaning:"支持者、弁護者", note:"≒ proponent", section:1 },
  { id:"0034", word:"trait", phonetic:"treɪt", pos:"名詞", meaning:"資質、特性", note:"= characteristic", section:1 },
  { id:"0035", word:"perspective", phonetic:"pəˈspektɪv", pos:"名詞", meaning:"観点、視野", note:"= viewpoint, standpoint", section:1 },
  { id:"0036", word:"stem", phonetic:"stem", pos:"名詞", meaning:"茎", note:"動 〜から生じる（from）", section:1 },
  { id:"0037", word:"component", phonetic:"kəmˈpoʊnənt", pos:"名詞", meaning:"構成部品、構成要素", note:"≒ constituent", section:1 },
  { id:"0038", word:"balance", phonetic:"ˈbæləns", pos:"名詞", meaning:"残高（≒ remainder）、均衡", note:"動 のバランスを保つ", section:1 },
  { id:"0039", word:"inmate", phonetic:"ˈɪnmeɪt", pos:"名詞", meaning:"（施設・刑務所などの）収容者", note:"person confined in a prison or institution", section:1 },
  { id:"0040", word:"extinction", phonetic:"ɪkˈstɪŋkʃən", pos:"名詞", meaning:"絶滅", note:"≒ disappearance; extinct 形", section:1 },
  { id:"0041", word:"proponent", phonetic:"prəˈpoʊnənt", pos:"名詞", meaning:"支持者、提唱者", note:"≒ adherent; ⇔ opponent", section:1 },
  { id:"0042", word:"uprising", phonetic:"ˈʌprɪzɪŋ", pos:"名詞", meaning:"反乱、暴動", note:"≒ rebellion, revolt", section:1 },
  { id:"0043", word:"perception", phonetic:"pəˈsepʃən", pos:"名詞", meaning:"認識、知覚", note:"perceive 動; perceptive 形", section:1 },
  { id:"0044", word:"habitat", phonetic:"ˈhæbɪtæt", pos:"名詞", meaning:"生息地、現地", note:"", section:1 },
  { id:"0045", word:"bias", phonetic:"ˈbaɪəs", pos:"名詞", meaning:"えこひいき、先入観", note:"≒ partiality; ≒ prejudice; ≒ tendency", section:1 },
  { id:"0046", word:"microbe", phonetic:"ˈmaɪkroʊb", pos:"名詞", meaning:"病原微生物", note:"≒ microorganism", section:1 },
  { id:"0047", word:"archaeologist", phonetic:"ˌɑːrkiˈɒlədʒɪst", pos:"名詞", meaning:"考古学者", note:"archaeology 名", section:1 },
  { id:"0048", word:"mutation", phonetic:"mjuːˈteɪʃən", pos:"名詞", meaning:"変異型", note:"≒ transformation; mutation gene 突然変異遺伝子", section:1 },
  { id:"0049", word:"attribute", phonetic:"ˈætrɪbjuːt", pos:"名詞", meaning:"特質、属性", note:"attributable 形 〜に起因する", section:1 },
  { id:"0050", word:"nanoparticle", phonetic:"ˈnænoʊˌpɑːrtɪkl", pos:"名詞", meaning:"ナノ粒子", note:"", section:1 },
  { id:"0051", word:"regime", phonetic:"reɪˈʒiːm", pos:"名詞", meaning:"政権、体制", note:"= reins of government; = system of government", section:1 },
  { id:"0052", word:"algorithm", phonetic:"ˈælɡərɪðəm", pos:"名詞", meaning:"アルゴリズム", note:"", section:1 },
  { id:"0053", word:"vet", phonetic:"vet", pos:"名詞", meaning:"獣医師", note:"= animal doctor; veterinarian 名", section:1 },
  { id:"0054", word:"dispute", phonetic:"dɪˈspjuːt", pos:"名詞", meaning:"争議、論争", note:"≒ controversy, argument; disputable 形", section:1 },
  { id:"0055", word:"migration", phonetic:"maɪˈɡreɪʃən", pos:"名詞", meaning:"移住", note:"= relocation; migration of birds 鳥の移動", section:1 },
  { id:"0056", word:"laborer", phonetic:"ˈleɪbərər", pos:"名詞", meaning:"（肉体）労働者", note:"= physical worker", section:1 },
  { id:"0057", word:"prohibition", phonetic:"ˌprəʊɪˈbɪʃən", pos:"名詞", meaning:"禁止", note:"prohibit 動; prohibitive 形", section:1 },
  { id:"0058", word:"reservoir", phonetic:"ˈrezəvwɑːr", pos:"名詞", meaning:"貯水池、知識の宝庫", note:"reservoir of knowledge 知識の宝庫", section:1 },
  { id:"0059", word:"founder", phonetic:"ˈfaʊndər", pos:"名詞", meaning:"創設者、創立者", note:"", section:1 },
  { id:"0060", word:"inhabitant", phonetic:"ɪnˈhæbɪtənt", pos:"名詞", meaning:"住民", note:"= resident", section:1 },
  { id:"0061", word:"commitment", phonetic:"kəˈmɪtmənt", pos:"名詞", meaning:"責任、献身", note:"= responsibility; = devotion", section:1 },
  { id:"0062", word:"rebellion", phonetic:"rɪˈbeljən", pos:"名詞", meaning:"反乱、暴動", note:"rise in rebellion 暴動を起こす", section:1 },
  { id:"0063", word:"capitalism", phonetic:"ˈkæpɪtəlɪzəm", pos:"名詞", meaning:"資本主義", note:"capitalist 形", section:1 },
  { id:"0064", word:"crack", phonetic:"kræk", pos:"名詞", meaning:"割れ目、ひび、隙間", note:"", section:1 },
  { id:"0065", word:"hydrogen", phonetic:"ˈhaɪdrədʒən", pos:"名詞", meaning:"水素", note:"cf. oxygen 酸素; nitrogen 窒素", section:1 },
  { id:"0066", word:"slavery", phonetic:"ˈsleɪvəri", pos:"名詞", meaning:"奴隷制度、捕われた状態", note:"", section:1 },
  { id:"0067", word:"warfare", phonetic:"ˈwɔːrfeər", pos:"名詞", meaning:"戦争（行為）、交戦状態", note:"biological warfare 生物戦", section:1 },
  { id:"0068", word:"criterion", phonetic:"kraɪˈtɪəriən", pos:"名詞", meaning:"基準、標準", note:"meet a criterion 基準を満たす", section:1 },
  { id:"0069", word:"asset", phonetic:"ˈæset", pos:"名詞", meaning:"資産、長所", note:"= resources; = strong point; cultural asset 文化遺産", section:1 },
  { id:"0070", word:"conviction", phonetic:"kənˈvɪkʃən", pos:"名詞", meaning:"確信、有罪の判決", note:"convince 動; convict 動", section:1 },
  { id:"0071", word:"corruption", phonetic:"kəˈrʌpʃən", pos:"名詞", meaning:"（道徳的）腐敗、不正行為", note:"corrupt 形", section:1 },
  { id:"0072", word:"legacy", phonetic:"ˈleɡəsi", pos:"名詞", meaning:"（過去からの）遺産、先人から受け継いだもの", note:"≒ inheritance", section:1 },
  { id:"0073", word:"offender", phonetic:"əˈfendər", pos:"名詞", meaning:"犯罪者", note:"= criminal; repeat offender 再犯者", section:1 },
  { id:"0074", word:"propaganda", phonetic:"ˌprɒpəˈɡændə", pos:"名詞", meaning:"プロパガンダ、宣伝活動", note:"", section:1 },
  { id:"0075", word:"republic", phonetic:"rɪˈpʌblɪk", pos:"名詞", meaning:"共和国", note:"⇔ monarchy 君主国; republican 形", section:1 },
  { id:"0076", word:"telescope", phonetic:"ˈtelɪskoʊp", pos:"名詞", meaning:"望遠鏡", note:"cf. binoculars 双眼鏡", section:1 },
  { id:"0077", word:"humanity", phonetic:"hjuːˈmænɪti", pos:"名詞", meaning:"人文科学、人類、人間性", note:"", section:1 },
  { id:"0078", word:"immunization", phonetic:"ˌɪmjuːnɪˈzeɪʃən", pos:"名詞", meaning:"予防接種", note:"immunize 動", section:1 },
  { id:"0079", word:"islander", phonetic:"ˈaɪləndər", pos:"名詞", meaning:"島民", note:"= resident on an island", section:1 },
  { id:"0080", word:"vent", phonetic:"vent", pos:"名詞", meaning:"通気孔、穴、はけ口", note:"= air hole; = aperture; = outlet, escape", section:1 },
  { id:"0081", word:"incentive", phonetic:"ɪnˈsentɪv", pos:"名詞", meaning:"刺激、誘因、報奨金", note:"= stimulus, spur, encouragement", section:1 },
  { id:"0082", word:"prosecutor", phonetic:"ˈprɒsɪkjuːtər", pos:"名詞", meaning:"検察官", note:"prosecution 名", section:1 },
  { id:"0083", word:"potential", phonetic:"pəˈtenʃl", pos:"形容詞", meaning:"潜在的な", note:"= latent; ⇔ actual; potential abilities 潜在的な能力", section:1 },
  { id:"0084", word:"indigenous", phonetic:"ɪnˈdɪdʒɪnəs", pos:"形容詞", meaning:"土着の、（その土地の）固有の", note:"= native; = innate", section:1 },
  { id:"0085", word:"enormous", phonetic:"ɪˈnɔːrməs", pos:"形容詞", meaning:"巨大な", note:"= huge; enormous capital 巨額の資本", section:1 },
  { id:"0086", word:"widespread", phonetic:"ˈwaɪdspred", pos:"形容詞", meaning:"広範な、広く知れ渡った", note:"= extensive; = well-known", section:1 },
  { id:"0087", word:"inevitable", phonetic:"ɪnˈevɪtəbl", pos:"形容詞", meaning:"避けられない", note:"= unavoidable; inevitably 副", section:1 },
  { id:"0088", word:"extinct", phonetic:"ɪkˈstɪŋkt", pos:"形容詞", meaning:"絶滅した、死に絶えた", note:"extinction 名", section:1 },
  { id:"0089", word:"electoral", phonetic:"ɪˈlektərəl", pos:"形容詞", meaning:"選挙の", note:"electoral system 選挙制度", section:1 },
  { id:"0090", word:"subsequent", phonetic:"ˈsʌbsɪkwənt", pos:"形容詞", meaning:"その後の", note:"subsequently 副; ≒ succeeding", section:1 },
  { id:"0091", word:"controversial", phonetic:"ˌkɒntrəˈvɜːʃl", pos:"形容詞", meaning:"論争を起こす", note:"controversial subject 物議をかもすテーマ", section:1 },
  { id:"0092", word:"disruptive", phonetic:"dɪsˈrʌptɪv", pos:"形容詞", meaning:"固定観念を壊す、混乱をもたらす", note:"disrupt 動", section:1 },
  { id:"0093", word:"robotic", phonetic:"roʊˈbɒtɪk", pos:"形容詞", meaning:"ロボットの、ロボットのような", note:"robotic engineering ロボット工学", section:1 },
  { id:"0094", word:"toxic", phonetic:"ˈtɒksɪk", pos:"形容詞", meaning:"有毒な", note:"= poisonous; toxic action 毒性の作用", section:1 },
  { id:"0095", word:"domesticated", phonetic:"dəˈmestɪkeɪtɪd", pos:"形容詞", meaning:"家畜化された、飼いならされた", note:"⇔ wild 野生の; domestication 名", section:1 },
  { id:"0096", word:"left-wing", phonetic:"ˈleftwɪŋ", pos:"形容詞", meaning:"左翼の、左派の", note:"⇔ right-wing", section:1 },
  { id:"0097", word:"ultimately", phonetic:"ˈʌltɪmətli", pos:"副詞", meaning:"最終的には", note:"= eventually, finally", section:1 },
  { id:"0098", word:"initially", phonetic:"ɪˈnɪʃəli", pos:"副詞", meaning:"最初は", note:"= firstly, at first", section:1 },
  { id:"0099", word:"genetically", phonetic:"dʒɪˈnetɪkli", pos:"副詞", meaning:"遺伝的に", note:"genetics 名; genetically modified food 遺伝子組み換え食品", section:1 },
  { id:"0100", word:"inherently", phonetic:"ɪnˈhɪərəntli", pos:"副詞", meaning:"本来、生まれつき", note:"inherent 形 固有の", section:1 },

  // Section 2 (0101-0200)
  { id:"0101", word:"cast", phonetic:"kɑːst", pos:"動詞", meaning:"（疑惑など）を投げかける（on ~に）", note:"名 配役", section:2 },
  { id:"0102", word:"supplement", phonetic:"ˈsʌplɪment", pos:"動詞", meaning:"を補う、に付け加える", note:"≒ complement; supplementary 形", section:2 },
  { id:"0103", word:"outweigh", phonetic:"ˌaʊtˈweɪ", pos:"動詞", meaning:"より価値がある、より重要である", note:"≒ be more important than", section:2 },
  { id:"0104", word:"implant", phonetic:"ɪmˈplɑːnt", pos:"動詞", meaning:"を埋め込む（in ~に）", note:"≒ insert; 名 インプラント", section:2 },
  { id:"0105", word:"enhance", phonetic:"ɪnˈhɑːns", pos:"動詞", meaning:"を高める", note:"≒ heighten, augment; enhancement 名", section:2 },
  { id:"0106", word:"revise", phonetic:"rɪˈvaɪz", pos:"動詞", meaning:"を改訂する、を改正する", note:"revision 名", section:2 },
  { id:"0107", word:"contend", phonetic:"kənˈtend", pos:"動詞", meaning:"戦う、主張する", note:"≒ compete; contention 名", section:2 },
  { id:"0108", word:"execute", phonetic:"ˈeksɪkjuːt", pos:"動詞", meaning:"を実行する、を死刑にする", note:"execution 名; executive 名 重役", section:2 },
  { id:"0109", word:"undermine", phonetic:"ˌʌndərˈmaɪn", pos:"動詞", meaning:"をひそかに傷つける、の下を掘る", note:"", section:2 },
  { id:"0110", word:"administer", phonetic:"ədˈmɪnɪstər", pos:"動詞", meaning:"を運営する、を施行する", note:"≒ manage; ≒ implement; administrative 形", section:2 },
  { id:"0111", word:"suspend", phonetic:"səˈspend", pos:"動詞", meaning:"を一時中断する、をつるす", note:"suspension 名", section:2 },
  { id:"0112", word:"cease", phonetic:"siːs", pos:"動詞", meaning:"を終える、終わる", note:"= come to an end; cease fire 停戦する", section:2 },
  { id:"0113", word:"assault", phonetic:"əˈsɔːlt", pos:"動詞", meaning:"に暴行する、を攻撃する", note:"名 暴行; 攻撃", section:2 },
  { id:"0114", word:"lobby", phonetic:"ˈlɒbi", pos:"動詞", meaning:"ロビー活動をする（for ~をめざして）", note:"名 ロビー", section:2 },
  { id:"0115", word:"torture", phonetic:"ˈtɔːrtʃər", pos:"動詞", meaning:"を拷問する", note:"名 拷問", section:2 },
  { id:"0116", word:"envision", phonetic:"ɪnˈvɪʒən", pos:"動詞", meaning:"を心に思い描く", note:"≒ imagine, picture", section:2 },
  { id:"0117", word:"govern", phonetic:"ˈɡʌvərn", pos:"動詞", meaning:"を統治する、を支配する", note:"governance 名; governor 名 知事", section:2 },
  { id:"0118", word:"reconsider", phonetic:"ˌriːkənˈsɪdər", pos:"動詞", meaning:"を再考する", note:"reconsideration 名", section:2 },
  { id:"0119", word:"enzyme", phonetic:"ˈenzaɪm", pos:"名詞", meaning:"酵素", note:"enzyme action 酵素作用", section:2 },
  { id:"0120", word:"faculty", phonetic:"ˈfækəlti", pos:"名詞", meaning:"能力、才能、教授陣", note:"= ability, talent", section:2 },
  { id:"0121", word:"predator", phonetic:"ˈpredətər", pos:"名詞", meaning:"捕食動物、略奪者", note:"≒ prey 獲物", section:2 },
  { id:"0122", word:"execution", phonetic:"ˌeksɪˈkjuːʃən", pos:"名詞", meaning:"死刑執行、実行", note:"executioner 名 死刑執行人", section:2 },
  { id:"0123", word:"implication", phonetic:"ˌɪmplɪˈkeɪʃən", pos:"名詞", meaning:"（通例~s）暗示、ほのめかし", note:"≒ effect", section:2 },
  { id:"0124", word:"interpretation", phonetic:"ɪnˌtɜːrprɪˈteɪʃən", pos:"名詞", meaning:"解釈、説明", note:"interpret 動; interpreter 名 通訳者", section:2 },
  { id:"0125", word:"extent", phonetic:"ɪkˈstent", pos:"名詞", meaning:"程度、範囲、広さ", note:"to an extent ある程度まで", section:2 },
  { id:"0126", word:"pyramid", phonetic:"ˈpɪrəmɪd", pos:"名詞", meaning:"ピラミッド", note:"", section:2 },
  { id:"0127", word:"midwife", phonetic:"ˈmɪdwaɪf", pos:"名詞", meaning:"助産師", note:"", section:2 },
  { id:"0128", word:"hypothesis", phonetic:"haɪˈpɒθəsɪs", pos:"名詞", meaning:"仮説", note:"= theory; hypothetical 形", section:2 },
  { id:"0129", word:"canal", phonetic:"kəˈnæl", pos:"名詞", meaning:"運河", note:"the Panama Canal パナマ運河", section:2 },
  { id:"0130", word:"communism", phonetic:"ˈkɒmjunɪzəm", pos:"名詞", meaning:"共産主義", note:"communist 形", section:2 },
  { id:"0131", word:"compensation", phonetic:"ˌkɒmpənˈseɪʃən", pos:"名詞", meaning:"補償、補填", note:"compensate 動", section:2 },
  { id:"0132", word:"consideration", phonetic:"kənˌsɪdəˈreɪʃən", pos:"名詞", meaning:"考慮、検討", note:"leave out of consideration 考慮から外す", section:2 },
  { id:"0133", word:"corps", phonetic:"kɔːr", pos:"名詞", meaning:"（しばしば Corps）部隊、軍団", note:"", section:2 },
  { id:"0134", word:"environmentalist", phonetic:"ɪnˌvaɪrənˈmentlɪst", pos:"名詞", meaning:"環境保護論者", note:"", section:2 },
  { id:"0135", word:"nationalist", phonetic:"ˈnæʃənəlɪst", pos:"名詞", meaning:"国家主義者、ナショナリスト", note:"", section:2 },
  { id:"0136", word:"offspring", phonetic:"ˈɒfsprɪŋ", pos:"名詞", meaning:"（集合的に）子、子孫", note:"≒ parent", section:2 },
  { id:"0137", word:"variation", phonetic:"ˌveəriˈeɪʃən", pos:"名詞", meaning:"変動、変化、変種", note:"", section:2 },
  { id:"0138", word:"veteran", phonetic:"ˈvetərən", pos:"名詞", meaning:"退役軍人、ベテラン", note:"= ex-serviceman", section:2 },
  { id:"0139", word:"eyewitness", phonetic:"ˈaɪwɪtnəs", pos:"名詞", meaning:"目撃者", note:"eyewitness testimony 目撃者の証言", section:2 },
  { id:"0140", word:"tactic", phonetic:"ˈtæktɪk", pos:"名詞", meaning:"（~s）戦略、作戦", note:"tactical 形", section:2 },
  { id:"0141", word:"altruism", phonetic:"ˈæltruɪzəm", pos:"名詞", meaning:"利他主義、利他心", note:"≒ regard for others; ⇔ selfishness; altruistic 形", section:2 },
  { id:"0142", word:"pesticide", phonetic:"ˈpestɪsaɪd", pos:"名詞", meaning:"農薬", note:"= chemical substance to kill insects; herbicide 除草剤", section:2 },
  { id:"0143", word:"commodity", phonetic:"kəˈmɒdɪti", pos:"名詞", meaning:"商品、生活必需品", note:"≒ merchandise", section:2 },
  { id:"0144", word:"accusation", phonetic:"ˌækjuːˈzeɪʃən", pos:"名詞", meaning:"告訴、非難", note:"make an accusation of A against B AをBに対して告訴する", section:2 },
  { id:"0145", word:"density", phonetic:"ˈdensɪti", pos:"名詞", meaning:"密度、密集、濃度", note:"", section:2 },
  { id:"0146", word:"mantle", phonetic:"ˈmæntl", pos:"名詞", meaning:"（地球の）マントル", note:"", section:2 },
  { id:"0147", word:"homeopathy", phonetic:"ˌhoʊmiˈɒpəθi", pos:"名詞", meaning:"ホメオパシー、同種療法", note:"", section:2 },
  { id:"0148", word:"obstetrician", phonetic:"ˌɒbstəˈtrɪʃən", pos:"名詞", meaning:"産科医", note:"obstetrics 名 産科; cf. ob-gyn 産婦人科医", section:2 },
  { id:"0149", word:"detection", phonetic:"dɪˈtekʃən", pos:"名詞", meaning:"探知、検出", note:"detector 名", section:2 },
  { id:"0150", word:"parasite", phonetic:"ˈpærəsaɪt", pos:"名詞", meaning:"寄生生物", note:"parasitic 形", section:2 },
  { id:"0151", word:"thesis", phonetic:"ˈθiːsɪs", pos:"名詞", meaning:"論文、論題", note:"= dissertation; master's thesis 修士論文", section:2 },
  { id:"0152", word:"coverage", phonetic:"ˈkʌvərɪdʒ", pos:"名詞", meaning:"報道、取材、報道範囲", note:"cover 動 を報道する", section:2 },
  { id:"0153", word:"resurrection", phonetic:"ˌrezəˈrekʃən", pos:"名詞", meaning:"復活", note:"= revival; resurrect 動", section:2 },
  { id:"0154", word:"molecule", phonetic:"ˈmɒlɪkjuːl", pos:"名詞", meaning:"分子", note:"cf. atom 原子; neutron 中性子", section:2 },
  { id:"0155", word:"sway", phonetic:"sweɪ", pos:"名詞", meaning:"支配、影響力", note:"= control, influence; hold sway over ~に力を持つ", section:2 },
  { id:"0156", word:"activist", phonetic:"ˈæktɪvɪst", pos:"名詞", meaning:"（政治的）活動家", note:"environmental activist 環境活動家", section:2 },
  { id:"0157", word:"certification", phonetic:"ˌsɜːrtɪfɪˈkeɪʃən", pos:"名詞", meaning:"証明書、証明", note:"= certificate", section:2 },
  { id:"0158", word:"complication", phonetic:"ˌkɒmplɪˈkeɪʃən", pos:"名詞", meaning:"（通例~s）合併症、複雑化する問題", note:"", section:2 },
  { id:"0159", word:"consensus", phonetic:"kənˈsensəs", pos:"名詞", meaning:"総意、大多数の意見", note:"= general agreement", section:2 },
  { id:"0160", word:"hostage", phonetic:"ˈhɒstɪdʒ", pos:"名詞", meaning:"人質", note:"take a person hostage （人）を人質に取る", section:2 },
  { id:"0161", word:"innocence", phonetic:"ˈɪnəsəns", pos:"名詞", meaning:"無罪、純真", note:"innocent 形", section:2 },
  { id:"0162", word:"journalism", phonetic:"ˈdʒɜːrnəlɪzəm", pos:"名詞", meaning:"ジャーナリズム", note:"journalist 名; journalistic 形", section:2 },
  { id:"0163", word:"landlord", phonetic:"ˈlændlɔːrd", pos:"名詞", meaning:"家主", note:"女性は landlady", section:2 },
  { id:"0164", word:"larva", phonetic:"ˈlɑːrvə", pos:"名詞", meaning:"幼虫", note:"cf. adult 成虫", section:2 },
  { id:"0165", word:"playwright", phonetic:"ˈpleɪraɪt", pos:"名詞", meaning:"劇作家", note:"= dramatist; screenwriter 脚本家", section:2 },
  { id:"0166", word:"relief", phonetic:"rɪˈliːf", pos:"名詞", meaning:"救援、安心、救済", note:"relieve 動", section:2 },
  { id:"0167", word:"representation", phonetic:"ˌreprɪzenˈteɪʃən", pos:"名詞", meaning:"代表、表示", note:"representative 形 典型的な", section:2 },
  { id:"0168", word:"senator", phonetic:"ˈsenətər", pos:"名詞", meaning:"上院議員", note:"cf. congressman 下院議員", section:2 },
  { id:"0169", word:"toxin", phonetic:"ˈtɒksɪn", pos:"名詞", meaning:"毒素", note:"= poisonous substance", section:2 },
  { id:"0170", word:"captor", phonetic:"ˈkæptər", pos:"名詞", meaning:"捕らえる人、捕獲者", note:"≒ captive 捕虜", section:2 },
  { id:"0171", word:"irradiation", phonetic:"ɪˌreɪdiˈeɪʃən", pos:"名詞", meaning:"放射線照射", note:"irradiate 動", section:2 },
  { id:"0172", word:"vulnerable", phonetic:"ˈvʌlnərəbl", pos:"形容詞", meaning:"傷つきやすい", note:"≒ susceptible; ≒ sensitive", section:2 },
  { id:"0173", word:"contemporary", phonetic:"kənˈtempərəri", pos:"形容詞", meaning:"現代の、同時代の", note:"≒ modern; contemporary writers 現代の作家", section:2 },
  { id:"0174", word:"crucial", phonetic:"ˈkruːʃl", pos:"形容詞", meaning:"重大な、決定的な", note:"= critical; = decisive; crucially 副", section:2 },
  { id:"0175", word:"forensic", phonetic:"fəˈrensɪk", pos:"形容詞", meaning:"犯罪捜査の、法廷の、法医学の", note:"forensic evidence 法医学的証拠", section:2 },
  { id:"0176", word:"colonial", phonetic:"kəˈloʊniəl", pos:"形容詞", meaning:"植民地の", note:"colonialist 名; colonialism 名", section:2 },
  { id:"0177", word:"magnetic", phonetic:"mæɡˈnetɪk", pos:"形容詞", meaning:"磁力の、磁気の", note:"magnetic force 磁力", section:2 },
  { id:"0178", word:"naval", phonetic:"ˈneɪvl", pos:"形容詞", meaning:"海軍の", note:"navy 名", section:2 },
  { id:"0179", word:"societal", phonetic:"səˈsaɪɪtl", pos:"形容詞", meaning:"社会の、社会に関する", note:"", section:2 },
  { id:"0180", word:"so-called", phonetic:"ˌsoʊˈkɔːld", pos:"形容詞", meaning:"いわゆる", note:"", section:2 },
  { id:"0181", word:"sophisticated", phonetic:"səˈfɪstɪkeɪtɪd", pos:"形容詞", meaning:"洗練された、複雑な", note:"= refined; sophistication 名", section:2 },
  { id:"0182", word:"sustainable", phonetic:"səˈsteɪnəbl", pos:"形容詞", meaning:"持続可能な、維持できる", note:"sustainability 名; sustainable development 持続可能な発展", section:2 },
  { id:"0183", word:"archaeological", phonetic:"ˌɑːrkiəˈlɒdʒɪkl", pos:"形容詞", meaning:"考古学の", note:"archaeologist 名", section:2 },
  { id:"0184", word:"diplomatic", phonetic:"ˌdɪpləˈmætɪk", pos:"形容詞", meaning:"外交の、駆け引きがうまい", note:"establish diplomatic relations 外交関係を樹立する", section:2 },
  { id:"0185", word:"literary", phonetic:"ˈlɪtərəri", pos:"形容詞", meaning:"文学の、文語的な", note:"literature 名", section:2 },
  { id:"0186", word:"Catholic", phonetic:"ˈkæθəlɪk", pos:"形容詞", meaning:"カトリックの", note:"Catholicism 名", section:2 },
  { id:"0187", word:"right-wing", phonetic:"ˈraɪtwɪŋ", pos:"形容詞", meaning:"右翼の、右派の", note:"⇔ left-wing", section:2 },
  { id:"0188", word:"dominant", phonetic:"ˈdɒmɪnənt", pos:"形容詞", meaning:"支配的な、主要な", note:"≒ influential, powerful; dominance 名", section:2 },
  { id:"0189", word:"infectious", phonetic:"ɪnˈfekʃəs", pos:"形容詞", meaning:"伝染性の", note:"= catching, easily transmitted; infection 名", section:2 },
  { id:"0190", word:"legitimate", phonetic:"lɪˈdʒɪtɪmɪt", pos:"形容詞", meaning:"道理にかなった、合法の", note:"= reasonable; = lawful; legitimacy 名", section:2 },
  { id:"0191", word:"tremendous", phonetic:"trɪˈmendəs", pos:"形容詞", meaning:"すさまじい", note:"= enormous", section:2 },
  { id:"0192", word:"cognitive", phonetic:"ˈkɒɡnɪtɪv", pos:"形容詞", meaning:"認知的な", note:"cognitive ability 認知能力", section:2 },
  { id:"0193", word:"critical", phonetic:"ˈkrɪtɪkl", pos:"形容詞", meaning:"批判的な、重大な", note:"criticize 動; criticism 名; critic 名 批評家", section:2 },
  { id:"0194", word:"architectural", phonetic:"ˌɑːrkɪˈtektʃərəl", pos:"形容詞", meaning:"建築的な、建築上の", note:"", section:2 },
  { id:"0195", word:"influential", phonetic:"ˌɪnflʊˈenʃl", pos:"形容詞", meaning:"大きな影響を及ぼす、有力な", note:"⇔ unimportant", section:2 },
  { id:"0196", word:"joint", phonetic:"dʒɔɪnt", pos:"形容詞", meaning:"共同の", note:"= united; joint responsibility 連帯責任", section:2 },
  { id:"0197", word:"pharmaceutical", phonetic:"ˌfɑːrməˈsuːtɪkl", pos:"形容詞", meaning:"製薬の", note:"cf. pharmacist 薬剤師", section:2 },
  { id:"0198", word:"ironically", phonetic:"aɪˈrɒnɪkli", pos:"副詞", meaning:"皮肉にも、皮肉なことに", note:"", section:2 },
  { id:"0199", word:"inevitably", phonetic:"ɪnˈevɪtəbli", pos:"副詞", meaning:"必然的に、必ず", note:"= unavoidably", section:2 },
  { id:"0200", word:"consequently", phonetic:"ˈkɒnsɪkwəntli", pos:"副詞", meaning:"その結果として", note:"= therefore, hence, thus", section:2 },

  // Section 3 (0201-0300)
  { id:"0201", word:"underestimate", phonetic:"ˌʌndərˈestɪmeɪt", pos:"動詞", meaning:"を過小評価する", note:"⇔ overestimate; underestimation 名", section:3 },
  { id:"0202", word:"trigger", phonetic:"ˈtrɪɡər", pos:"動詞", meaning:"を誘発する", note:"≒ precipitate, set off; 名 引き金", section:3 },
  { id:"0203", word:"diminish", phonetic:"dɪˈmɪnɪʃ", pos:"動詞", meaning:"減少する、を減らす", note:"≒ reduce, lessen; diminution 名", section:3 },
  { id:"0204", word:"reinforce", phonetic:"ˌriːɪnˈfɔːrs", pos:"動詞", meaning:"を強化する", note:"≒ strengthen, fortify; reinforcement 名", section:3 },
  { id:"0205", word:"abolish", phonetic:"əˈbɒlɪʃ", pos:"動詞", meaning:"を廃止する", note:"= do away with; abolition 名", section:3 },
  { id:"0206", word:"exonerate", phonetic:"ɪɡˈzɒnəreɪt", pos:"動詞", meaning:"の疑いを晴らす、を免除する", note:"exoneration 名", section:3 },
  { id:"0207", word:"perish", phonetic:"ˈperɪʃ", pos:"動詞", meaning:"死亡する、滅びる", note:"perishable 形 腐りやすい", section:3 },
  { id:"0208", word:"halt", phonetic:"hɔːlt", pos:"動詞", meaning:"止まる、を止める", note:"= stop; halt traffic 交通をとめる", section:3 },
  { id:"0209", word:"extract", phonetic:"ɪkˈstrækt", pos:"動詞", meaning:"を取り出す、を引用する", note:"名 抜粋; extraction 名", section:3 },
  { id:"0210", word:"decay", phonetic:"dɪˈkeɪ", pos:"動詞", meaning:"腐敗する、崩壊する", note:"≒ rot; ≒ disintegrate", section:3 },
  { id:"0211", word:"resume", phonetic:"rɪˈzjuːm", pos:"動詞", meaning:"再開する", note:"= start again; resumption 名", section:3 },
  { id:"0212", word:"cultivate", phonetic:"ˈkʌltɪveɪt", pos:"動詞", meaning:"を栽培する、（才能を）養う", note:"≒ grow; cultivation 名", section:3 },
  { id:"0213", word:"depict", phonetic:"dɪˈpɪkt", pos:"動詞", meaning:"を描写する", note:"≒ describe; depiction 名", section:3 },
  { id:"0214", word:"entitle", phonetic:"ɪnˈtaɪtl", pos:"動詞", meaning:"に（権利）を与える", note:"entitlement 名 権利", section:3 },
  { id:"0215", word:"lease", phonetic:"liːs", pos:"動詞", meaning:"をリースで貸借する", note:"= rent", section:3 },
  { id:"0216", word:"oversee", phonetic:"ˌoʊvərˈsiː", pos:"動詞", meaning:"を監督する", note:"= supervise; overseer 名", section:3 },
  { id:"0217", word:"regain", phonetic:"rɪˈɡeɪn", pos:"動詞", meaning:"を取り戻す、を回復する", note:"= recover, get back", section:3 },
  { id:"0218", word:"comprise", phonetic:"kəmˈpraɪz", pos:"動詞", meaning:"を構成する", note:"be comprised of ~で構成される; = constitute, make up", section:3 },
  { id:"0219", word:"dismantle", phonetic:"dɪsˈmæntl", pos:"動詞", meaning:"を分解する", note:"= take apart", section:3 },
  { id:"0220", word:"infer", phonetic:"ɪnˈfɜːr", pos:"動詞", meaning:"を推論する（from ~から）", note:"= deduce; inference 名", section:3 },
  { id:"0221", word:"deploy", phonetic:"dɪˈplɔɪ", pos:"動詞", meaning:"を配置する、（軍事）を展開させる", note:"deployment 名", section:3 },
  { id:"0222", word:"ignite", phonetic:"ɪɡˈnaɪt", pos:"動詞", meaning:"に火をつける、（感情を）燃え立たせる", note:"ignition 名", section:3 },
  { id:"0223", word:"methane", phonetic:"ˈmiːθeɪn", pos:"名詞", meaning:"メタン", note:"", section:3 },
  { id:"0224", word:"rodent", phonetic:"ˈroʊdənt", pos:"名詞", meaning:"齧歯類動物", note:"", section:3 },
  { id:"0225", word:"enforcement", phonetic:"ɪnˈfɔːrsmənt", pos:"名詞", meaning:"施行、実施", note:"enforce 動", section:3 },
  { id:"0226", word:"peer", phonetic:"pɪər", pos:"名詞", meaning:"仲間、同輩、（英国の）貴族", note:"= equal; peerless 形 並ぶ者がない", section:3 },
  { id:"0227", word:"forgery", phonetic:"ˈfɔːrdʒəri", pos:"名詞", meaning:"偽造（書）、偽造品", note:"= counterfeit; forge 動 偽造する", section:3 },
  { id:"0228", word:"agenda", phonetic:"əˈdʒendə", pos:"名詞", meaning:"協議事項（リスト）", note:"a list of things to be dealt with at a meeting", section:3 },
  { id:"0229", word:"contamination", phonetic:"kənˌtæmɪˈneɪʃən", pos:"名詞", meaning:"汚染", note:"= pollution; contaminate 動", section:3 },
  { id:"0230", word:"composition", phonetic:"ˌkɒmpəˈzɪʃən", pos:"名詞", meaning:"組成、構成、楽曲", note:"compose 動", section:3 },
  { id:"0231", word:"constituent", phonetic:"kənˈstɪtʃuənt", pos:"名詞", meaning:"選挙区民、成分", note:"constituency 名 選挙区", section:3 },
  { id:"0232", word:"counselor", phonetic:"ˈkaʊnsələr", pos:"名詞", meaning:"カウンセラー、相談員", note:"guidance counselor 進路相談員", section:3 },
  { id:"0233", word:"coup", phonetic:"kuː", pos:"名詞", meaning:"クーデター", note:"= coup d'état; coup attempt クーデター未遂", section:3 },
  { id:"0234", word:"glue", phonetic:"ɡluː", pos:"名詞", meaning:"接着剤", note:"= adhesive", section:3 },
  { id:"0235", word:"philosopher", phonetic:"fɪˈlɒsəfər", pos:"名詞", meaning:"哲学者", note:"", section:3 },
  { id:"0236", word:"psychiatrist", phonetic:"saɪˈkaɪətrɪst", pos:"名詞", meaning:"精神科医", note:"psychiatry 名 精神医学", section:3 },
  { id:"0237", word:"socialist", phonetic:"ˈsoʊʃəlɪst", pos:"名詞", meaning:"社会主義者", note:"socialism 名", section:3 },
  { id:"0238", word:"specification", phonetic:"ˌspesɪfɪˈkeɪʃən", pos:"名詞", meaning:"（通例~s）製品仕様、スペック", note:"= spec", section:3 },
  { id:"0239", word:"stimulus", phonetic:"ˈstɪmjʊləs", pos:"名詞", meaning:"刺激", note:"= response 反応; stimulate 動", section:3 },
  { id:"0240", word:"stockpile", phonetic:"ˈstɒkpaɪl", pos:"名詞", meaning:"（食品・兵器などの）備蓄", note:"動 を備蓄する", section:3 },
  { id:"0241", word:"watershed", phonetic:"ˈwɔːtərʃed", pos:"名詞", meaning:"分水嶺", note:"", section:3 },
  { id:"0242", word:"mortality", phonetic:"mɔːrˈtælɪti", pos:"名詞", meaning:"死亡率、死ぬ運命", note:"mortal 形; ⇔ immortality 不死", section:3 },
  { id:"0243", word:"premium", phonetic:"ˈpriːmiəm", pos:"名詞", meaning:"割増金、保険料", note:"= reward; = payment for insurance", section:3 },
  { id:"0244", word:"myriad", phonetic:"ˈmɪriəd", pos:"名詞", meaning:"無数（の）", note:"a myriad of 〜の無数の", section:3 },
  { id:"0245", word:"phase", phonetic:"feɪz", pos:"名詞", meaning:"段階、局面", note:"= stage; = aspect, side, part", section:3 },
  { id:"0246", word:"tenure", phonetic:"ˈtenjər", pos:"名詞", meaning:"（大学教員の）終身在職権、保有（期間）", note:"", section:3 },
  { id:"0247", word:"quota", phonetic:"ˈkwoʊtə", pos:"名詞", meaning:"割り当て量、ノルマ", note:"= norm", section:3 },
  { id:"0248", word:"assessment", phonetic:"əˈsesmənt", pos:"名詞", meaning:"査定、評価", note:"= appraisal, rating; assess 動; environmental assessment 環境影響評価", section:3 },
  { id:"0249", word:"intervention", phonetic:"ˌɪntərˈvenʃən", pos:"名詞", meaning:"介入、仲裁", note:"= intercession; government intervention 政府の介入", section:3 },
  { id:"0250", word:"alliance", phonetic:"əˈlaɪəns", pos:"名詞", meaning:"同盟、提携", note:"= association; ally 名", section:3 },
  { id:"0251", word:"projection", phonetic:"prəˈdʒekʃən", pos:"名詞", meaning:"予測", note:"= forecast; economic projection 経済成長予測", section:3 },
  { id:"0252", word:"scheme", phonetic:"skiːm", pos:"名詞", meaning:"たくらみ、計画", note:"= plan; business scheme 事業計画", section:3 },
  { id:"0253", word:"bid", phonetic:"bɪd", pos:"名詞", meaning:"試み、入札", note:"takeover bid 株式公開買い付け（TOB）", section:3 },
  { id:"0254", word:"brutality", phonetic:"bruːˈtælɪti", pos:"名詞", meaning:"残忍さ、野蛮性", note:"= cruelty, ruthlessness", section:3 },
  { id:"0255", word:"conquest", phonetic:"ˈkɒŋkwest", pos:"名詞", meaning:"征服、征服したもの", note:"conquer 動", section:3 },
  { id:"0256", word:"contractor", phonetic:"ˈkɒntræktər", pos:"名詞", meaning:"請負業者", note:"cf. subcontractor 下請け業者", section:3 },
  { id:"0257", word:"correction", phonetic:"kəˈrekʃən", pos:"名詞", meaning:"訂正、修正", note:"corrective 形", section:3 },
  { id:"0258", word:"crust", phonetic:"krʌst", pos:"名詞", meaning:"地殻、パンの皮", note:"", section:3 },
  { id:"0259", word:"hostility", phonetic:"hɒˈstɪlɪti", pos:"名詞", meaning:"敵対、反感", note:"= unfriendly attitude; hostile 形", section:3 },
  { id:"0260", word:"imprisonment", phonetic:"ɪmˈprɪzənmənt", pos:"名詞", meaning:"投獄、監禁", note:"= incarceration; life imprisonment 終身刑", section:3 },
  { id:"0261", word:"initiative", phonetic:"ɪˈnɪʃɪətɪv", pos:"名詞", meaning:"重要な新計画、主導権", note:"have the initiative 主導権を持つ", section:3 },
  { id:"0262", word:"injection", phonetic:"ɪnˈdʒekʃən", pos:"名詞", meaning:"注射", note:"= shot; give a person an injection （人）に注射する", section:3 },
  { id:"0263", word:"manipulation", phonetic:"məˌnɪpjʊˈleɪʃən", pos:"名詞", meaning:"（巧妙な）操作", note:"genetic manipulation 遺伝子操作", section:3 },
  { id:"0264", word:"mate", phonetic:"meɪt", pos:"名詞", meaning:"つがいの相手", note:"動 交尾する", section:3 },
  { id:"0265", word:"morality", phonetic:"məˈrælɪti", pos:"名詞", meaning:"道徳、倫理", note:"moral 形; a sense of morality 道徳観", section:3 },
  { id:"0266", word:"reliance", phonetic:"rɪˈlaɪəns", pos:"名詞", meaning:"依存", note:"= dependence; reliant 形", section:3 },
  { id:"0267", word:"sensitivity", phonetic:"ˌsensɪˈtɪvɪti", pos:"名詞", meaning:"敏感性、神経の細かさ", note:"sensitive 形", section:3 },
  { id:"0268", word:"sentiment", phonetic:"ˈsentɪmənt", pos:"名詞", meaning:"感情、心情、意見", note:"= attitude, mindset", section:3 },
  { id:"0269", word:"severity", phonetic:"sɪˈverɪti", pos:"名詞", meaning:"厳しさ、深刻さ", note:"= gravity; severe 形", section:3 },
  { id:"0270", word:"variant", phonetic:"ˈveəriənt", pos:"名詞", meaning:"変形、変種", note:"variation 名", section:3 },
  { id:"0271", word:"workload", phonetic:"ˈwɜːrkloʊd", pos:"名詞", meaning:"仕事の負担量", note:"heavy workload 大量の仕事", section:3 },
  { id:"0272", word:"fireplace", phonetic:"ˈfaɪərpleɪs", pos:"名詞", meaning:"暖炉", note:"", section:3 },
  { id:"0273", word:"gunpowder", phonetic:"ˈɡʌnpaʊdər", pos:"名詞", meaning:"火薬", note:"", section:3 },
  { id:"0274", word:"painkiller", phonetic:"ˈpeɪnkɪlər", pos:"名詞", meaning:"鎮痛剤、痛み止め", note:"", section:3 },
  { id:"0275", word:"zoology", phonetic:"zuːˈɒlədʒi", pos:"名詞", meaning:"動物学", note:"cf. botany 植物学", section:3 },
  { id:"0276", word:"stake", phonetic:"steɪk", pos:"名詞", meaning:"杭、投資・利権関係", note:"at stake 危うくなって", section:3 },
  { id:"0277", word:"pricey", phonetic:"ˈpraɪsi", pos:"形容詞", meaning:"高価な", note:"= expensive; ⇔ cheap", section:3 },
  { id:"0278", word:"cellular", phonetic:"ˈseljʊlər", pos:"形容詞", meaning:"細胞の", note:"", section:3 },
  { id:"0279", word:"considerable", phonetic:"kənˈsɪdərəbl", pos:"形容詞", meaning:"かなりの、相当な", note:"considerably 副; ≒ significant", section:3 },
  { id:"0280", word:"gifted", phonetic:"ˈɡɪftɪd", pos:"形容詞", meaning:"才能のある（特別の）", note:"= talented; be gifted with 〜の才能を持つ", section:3 },
  { id:"0281", word:"present-day", phonetic:"ˈprezntdeɪ", pos:"形容詞", meaning:"現代の、今日の", note:"= current", section:3 },
  { id:"0282", word:"illicit", phonetic:"ɪˈlɪsɪt", pos:"形容詞", meaning:"不法の、不正な", note:"= improper; = unlawful, illegal", section:3 },
  { id:"0283", word:"compelling", phonetic:"kəmˈpelɪŋ", pos:"形容詞", meaning:"説得力がある、前向きのいく", note:"= convincing", section:3 },
  { id:"0284", word:"skeptical", phonetic:"ˈskeptɪkl", pos:"形容詞", meaning:"懐疑的な", note:"= doubtful; skeptic 名", section:3 },
  { id:"0285", word:"authentic", phonetic:"ɔːˈθentɪk", pos:"形容詞", meaning:"本物の、確かな", note:"= genuine; ⇔ fake; authenticity 名", section:3 },
  { id:"0286", word:"inherent", phonetic:"ɪnˈhɪərənt", pos:"形容詞", meaning:"生来の、固有の", note:"= intrinsic, innate; one's inherent character 生まれながらの性格", section:3 },
  { id:"0287", word:"ethical", phonetic:"ˈeθɪkl", pos:"形容詞", meaning:"道徳にかなった", note:"= moral", section:3 },
  { id:"0288", word:"irrational", phonetic:"ɪˈræʃənl", pos:"形容詞", meaning:"訳のわからない、不合理な", note:"= unreasonable; irrational decision 非合理的な意思決定", section:3 },
  { id:"0289", word:"decent", phonetic:"ˈdiːsnt", pos:"形容詞", meaning:"かなりの、きちんとした", note:"decency 名 きちんとしていること", section:3 },
  { id:"0290", word:"civic", phonetic:"ˈsɪvɪk", pos:"形容詞", meaning:"市民としての、市の", note:"", section:3 },
  { id:"0291", word:"psychiatric", phonetic:"ˌsaɪkiˈætrɪk", pos:"形容詞", meaning:"精神医学の", note:"psychiatry 名", section:3 },
  { id:"0292", word:"racial", phonetic:"ˈreɪʃl", pos:"形容詞", meaning:"人種の", note:"racially 副", section:3 },
  { id:"0293", word:"sympathetic", phonetic:"ˌsɪmpəˈθetɪk", pos:"形容詞", meaning:"好意的な、同情的な", note:"sympathetically 副", section:3 },
  { id:"0294", word:"volcanic", phonetic:"vɒlˈkænɪk", pos:"形容詞", meaning:"火山の、火山地帯の", note:"volcanic activity 火山活動", section:3 },
  { id:"0295", word:"appealing", phonetic:"əˈpiːlɪŋ", pos:"形容詞", meaning:"魅力がある", note:"= attractive, pleasing", section:3 },
  { id:"0296", word:"decisive", phonetic:"dɪˈsaɪsɪv", pos:"形容詞", meaning:"断固とした、決断力のある", note:"decisively 副; ⇔ indecisive", section:3 },
  { id:"0297", word:"fundamentally", phonetic:"ˌfʌndəˈmentəli", pos:"副詞", meaning:"根本的に、基本的に", note:"", section:3 },
  { id:"0298", word:"interestingly", phonetic:"ˈɪntrɪstɪŋli", pos:"副詞", meaning:"興味深いことに", note:"", section:3 },
  { id:"0299", word:"simultaneously", phonetic:"ˌsɪməlˈteɪniəsli", pos:"副詞", meaning:"同時に", note:"= at the same time", section:3 },
  { id:"0300", word:"solely", phonetic:"ˈsoʊlli", pos:"副詞", meaning:"単独で、ただ、単に", note:"= only", section:3 },

  // ===== Section 4 (0301-0400) =====
  // --- 動詞 ---
  { id:"0301", word:"transmit", phonetic:"trænsˈmɪt", pos:"動詞", meaning:"伝達する、（~を）送る", note:"transmission 名 伝送、伝達", section:4 },
  { id:"0302", word:"retain", phonetic:"rɪˈteɪn", pos:"動詞", meaning:"保持する、を保つ", note:"≒ keep, maintain", section:4 },
  { id:"0303", word:"embrace", phonetic:"ɪmˈbreɪs", pos:"動詞", meaning:"を受け入れる、を抱きしめる", note:"≒ accept; ≒ hug", section:4 },
  { id:"0304", word:"allocate", phonetic:"ˈæləkeɪt", pos:"動詞", meaning:"を割り当てる、を配分する", note:"allocation 名 配分; ≒ allot", section:4 },
  { id:"0305", word:"expire", phonetic:"ɪkˈspaɪər", pos:"動詞", meaning:"期限が切れる、終了する", note:"≒ terminate; expiry 名 満期", section:4 },
  { id:"0306", word:"inhibit", phonetic:"ɪnˈhɪbɪt", pos:"動詞", meaning:"を抑制する、を妨げる", note:"≒ restrain, check, repress; inhibition 名 抑制", section:4 },
  { id:"0307", word:"gamble", phonetic:"ˈɡæmbl", pos:"動詞", meaning:"賭ける", note:"gamble that… という文脈で使う", section:4 },
  { id:"0308", word:"finalize", phonetic:"ˈfaɪnəlaɪz", pos:"動詞", meaning:"を仕上げる、完了する", note:"≒ finish, complete; finalization 名 確定", section:4 },
  { id:"0309", word:"hail", phonetic:"heɪl", pos:"動詞", meaning:"を称賛する、出身である", note:"hail from ~の出身である", section:4 },
  { id:"0310", word:"overthrow", phonetic:"ˌoʊvərˈθroʊ", pos:"動詞", meaning:"を転覆させる、を打倒する", note:"名 打倒、転覆", section:4 },
  { id:"0311", word:"resurrect", phonetic:"ˌrezəˈrekt", pos:"動詞", meaning:"を復活させる", note:"≒ revive, restore; resurrection 名 復活", section:4 },
  { id:"0312", word:"discriminate", phonetic:"dɪˈskrɪmɪneɪt", pos:"動詞", meaning:"差別する（against ~を）、区別する（between ~を）", note:"discriminating 形 識別力がある; discrimination 名 差別", section:4 },
  { id:"0313", word:"resonate", phonetic:"ˈrezəneɪt", pos:"動詞", meaning:"共感を呼び起こす（with ~に）", note:"resonance 名 共鳴", section:4 },
  { id:"0314", word:"harness", phonetic:"ˈhɑːrnɪs", pos:"動詞", meaning:"を利用する、に馬具を付ける", note:"名 馬具", section:4 },
  { id:"0315", word:"suppress", phonetic:"səˈpres", pos:"動詞", meaning:"を鎮圧する、を抑圧する", note:"≒ put down; suppression 名 鎮圧", section:4 },
  { id:"0316", word:"drain", phonetic:"dreɪn", pos:"動詞", meaning:"の水を引き出す", note:"drainage 名 排水; drain the bath water 湯を捨てる", section:4 },
  { id:"0317", word:"usher", phonetic:"ˈʌʃər", pos:"動詞", meaning:"を案内する（to ~へ）", note:"≒ escort; 名 案内係", section:4 },
  { id:"0318", word:"exploit", phonetic:"ɪkˈsplɔɪt", pos:"動詞", meaning:"を利用する（≒ take advantage of）、を搾取する", note:"exploitation 名 搾取; exploit workers 労働者を搾取する", section:4 },
  { id:"0319", word:"pitch", phonetic:"pɪtʃ", pos:"動詞", meaning:"（案・企画など）を売り込む（to ~に）", note:"名 売り込み", section:4 },
  { id:"0320", word:"slaughter", phonetic:"ˈslɔːtər", pos:"動詞", meaning:"を虐殺する、を屠殺する", note:"名 虐殺、屠殺", section:4 },
  { id:"0321", word:"enact", phonetic:"ɪˈnækt", pos:"動詞", meaning:"を制定する", note:"≒ ordain, decree; enactment 名 制定", section:4 },
  { id:"0322", word:"deter", phonetic:"dɪˈtɜːr", pos:"動詞", meaning:"に思いとどまらせる（from ~から）", note:"≒ prevent; deterrence 名 抑止力", section:4 },
  // --- 名詞 ---
  { id:"0323", word:"surveillance", phonetic:"sɜːrˈveɪləns", pos:"名詞", meaning:"監視、見張り", note:"≒ observation, scrutiny, guard", section:4 },
  { id:"0324", word:"mosaic", phonetic:"moʊˈzeɪɪk", pos:"名詞", meaning:"モザイク、異なるものの寄せ集め", note:"ethnic mosaic 民族のモザイク", section:4 },
  { id:"0325", word:"conspirator", phonetic:"kənˈspɪrətər", pos:"名詞", meaning:"陰謀者、共謀者", note:"conspiratorial 形 陰謀の", section:4 },
  { id:"0326", word:"influx", phonetic:"ˈɪnflʌks", pos:"名詞", meaning:"流入", note:"⇔ outflow 流出", section:4 },
  { id:"0327", word:"faction", phonetic:"ˈfækʃən", pos:"名詞", meaning:"派閥、グループ", note:"faction leader 派閥のリーダー", section:4 },
  { id:"0328", word:"expertise", phonetic:"ˌekspɜːrˈtiːz", pos:"名詞", meaning:"専門知識・技術", note:"business expertise ビジネスの専門知識", section:4 },
  { id:"0329", word:"diagnosis", phonetic:"ˌdaɪəɡˈnoʊsɪs", pos:"名詞", meaning:"診断", note:"make a wrong diagnosis 誤った診断をする", section:4 },
  { id:"0330", word:"utility", phonetic:"juːˈtɪlɪti", pos:"名詞", meaning:"（電気・ガス・水道などの）公益事業、有用性", note:"of utility 役に立つ", section:4 },
  { id:"0331", word:"collision", phonetic:"kəˈlɪʒən", pos:"名詞", meaning:"衝突", note:"collision between two buses バス2台の衝突", section:4 },
  { id:"0332", word:"coalition", phonetic:"ˌkoʊəˈlɪʃən", pos:"名詞", meaning:"連合、合同", note:"≒ alliance, partnership, league", section:4 },
  { id:"0333", word:"adoption", phonetic:"əˈdɒpʃən", pos:"名詞", meaning:"採用、採択、養子縁組", note:"adopt 動 採用する; 養子にする", section:4 },
  { id:"0334", word:"attorney", phonetic:"əˈtɜːrni", pos:"名詞", meaning:"弁護士", note:"≒ lawyer", section:4 },
  { id:"0335", word:"biodiversity", phonetic:"ˌbaɪoʊdaɪˈvɜːrsɪti", pos:"名詞", meaning:"生物多様性", note:"", section:4 },
  { id:"0336", word:"captivity", phonetic:"kæpˈtɪvɪti", pos:"名詞", meaning:"捕われの状態", note:"captive 形 捕われた", section:4 },
  { id:"0337", word:"carrier", phonetic:"ˈkæriər", pos:"名詞", meaning:"保菌者、輸送会社", note:"", section:4 },
  { id:"0338", word:"catering", phonetic:"ˈkeɪtərɪŋ", pos:"名詞", meaning:"ケータリング", note:"", section:4 },
  { id:"0339", word:"cement", phonetic:"sɪˈment", pos:"名詞", meaning:"セメント", note:"", section:4 },
  { id:"0340", word:"commander", phonetic:"kəˈmændər", pos:"名詞", meaning:"司令官、指揮官", note:"commander in chief 最高司令官", section:4 },
  { id:"0341", word:"coordination", phonetic:"koʊˌɔːrdɪˈneɪʃən", pos:"名詞", meaning:"調整、連携", note:"coordinate 動 調整する", section:4 },
  { id:"0342", word:"deterioration", phonetic:"dɪˌtɪəriəˈreɪʃən", pos:"名詞", meaning:"悪化、低下", note:"deteriorate 動 悪化する", section:4 },
  { id:"0343", word:"discomfort", phonetic:"dɪsˈkʌmfərt", pos:"名詞", meaning:"不快、不便", note:"have discomfort in one's chest 胸に不快感がある", section:4 },
  { id:"0344", word:"ethic", phonetic:"ˈeθɪk", pos:"名詞", meaning:"倫理、道徳", note:"ethical 形 倫理的な", section:4 },
  { id:"0345", word:"herd", phonetic:"hɜːrd", pos:"名詞", meaning:"（動物の）群れ", note:"cf. flock （羊・鳥などの）群れ; school （魚の）群れ", section:4 },
  { id:"0346", word:"implementation", phonetic:"ˌɪmplɪmenˈteɪʃən", pos:"名詞", meaning:"（計画・政策などの）実施、実行", note:"implement 動 実行する", section:4 },
  { id:"0347", word:"intent", phonetic:"ɪnˈtent", pos:"名詞", meaning:"意図、目的", note:"intentional 形 故意の", section:4 },
  { id:"0348", word:"pathogen", phonetic:"ˈpæθədʒən", pos:"名詞", meaning:"病原体、病原菌", note:"pathogenic 形 病原性の", section:4 },
  { id:"0349", word:"pension", phonetic:"ˈpenʃən", pos:"名詞", meaning:"年金", note:"live on one's pension 年金で生活する", section:4 },
  { id:"0350", word:"portrait", phonetic:"ˈpɔːrtrɪt", pos:"名詞", meaning:"肖像画、肖像写真", note:"cf. self-portrait 自画像", section:4 },
  { id:"0351", word:"prosecution", phonetic:"ˌprɒsɪˈkjuːʃən", pos:"名詞", meaning:"起訴、告訴", note:"prosecute 動 起訴する", section:4 },
  { id:"0352", word:"qualification", phonetic:"ˌkwɒlɪfɪˈkeɪʃən", pos:"名詞", meaning:"資格、資質", note:"qualified 形 資格を持った", section:4 },
  { id:"0353", word:"relevance", phonetic:"ˈreləvəns", pos:"名詞", meaning:"関連性、妥当性", note:"relevant 形 関連した", section:4 },
  { id:"0354", word:"reproduction", phonetic:"ˌriːprəˈdʌkʃən", pos:"名詞", meaning:"生殖、再生、複製", note:"sexual reproduction 有性生殖", section:4 },
  { id:"0355", word:"sediment", phonetic:"ˈsedɪmənt", pos:"名詞", meaning:"堆積物、沈殿物", note:"", section:4 },
  { id:"0356", word:"sociologist", phonetic:"ˌsoʊsiˈɒlədʒɪst", pos:"名詞", meaning:"社会学者", note:"sociology 名 社会学", section:4 },
  { id:"0357", word:"spacecraft", phonetic:"ˈspeɪskrɑːft", pos:"名詞", meaning:"宇宙船", note:"≒ spaceship", section:4 },
  { id:"0358", word:"terrorism", phonetic:"ˈterərɪzəm", pos:"名詞", meaning:"テロ、テロリズム", note:"terrorist 名 テロリスト; combat terrorism テロと戦う", section:4 },
  { id:"0359", word:"cornerstone", phonetic:"ˈkɔːrnərstoʊn", pos:"名詞", meaning:"基礎、土台", note:"", section:4 },
  { id:"0360", word:"janitor", phonetic:"ˈdʒænɪtər", pos:"名詞", meaning:"管理人、用務員", note:"≒ custodian, caretaker", section:4 },
  { id:"0361", word:"neuroscientist", phonetic:"ˌnjʊəroʊˈsaɪəntɪst", pos:"名詞", meaning:"神経科学者", note:"neuroscience 名 神経科学", section:4 },
  { id:"0362", word:"paleontologist", phonetic:"ˌpeɪliɒnˈtɒlədʒɪst", pos:"名詞", meaning:"古生物学者", note:"paleontology 名 古生物学", section:4 },
  { id:"0363", word:"reductionism", phonetic:"rɪˈdʌkʃənɪzəm", pos:"名詞", meaning:"還元主義", note:"reductionist 形 還元主義の", section:4 },
  { id:"0364", word:"screening", phonetic:"ˈskriːnɪŋ", pos:"名詞", meaning:"（特定疾患の）検診、（映画の）上映", note:"", section:4 },
  { id:"0365", word:"senescence", phonetic:"sɪˈnesəns", pos:"名詞", meaning:"老化", note:"senescent 形 老化の", section:4 },
  { id:"0366", word:"catalyst", phonetic:"ˈkætəlɪst", pos:"名詞", meaning:"きっかけ（for ~の）、触媒", note:"", section:4 },
  { id:"0367", word:"blight", phonetic:"blaɪt", pos:"名詞", meaning:"（植物が）枯れる病気、損なうもの、荒廃", note:"", section:4 },
  { id:"0368", word:"debris", phonetic:"dəˈbriː", pos:"名詞", meaning:"残骸、がれき", note:"", section:4 },
  { id:"0369", word:"cavity", phonetic:"ˈkævɪti", pos:"名詞", meaning:"強度の穴、虫歯", note:"nasal cavity 鼻腔", section:4 },
  { id:"0370", word:"liaison", phonetic:"liˈeɪzɒn", pos:"名詞", meaning:"連絡係、連絡関係、密通", note:"liaise 動 連絡をとる", section:4 },
  { id:"0371", word:"defect", phonetic:"ˈdiːfekt", pos:"名詞", meaning:"欠陥、欠点", note:"defective 形 欠陥のある", section:4 },
  { id:"0372", word:"incarceration", phonetic:"ɪnˌkɑːrsəˈreɪʃən", pos:"名詞", meaning:"投獄、拘禁", note:"incarcerate 動 を投獄する", section:4 },
  { id:"0373", word:"counterfeit", phonetic:"ˈkaʊntərfɪt", pos:"名詞", meaning:"偽造品、偽物", note:"偽の", section:4 },
  { id:"0374", word:"validity", phonetic:"vəˈlɪdɪti", pos:"名詞", meaning:"有効性、正当性", note:"valid 形 有効な", section:4 },
  // --- 形容詞 ---
  { id:"0375", word:"equivalent", phonetic:"ɪˈkwɪvələnt", pos:"形容詞", meaning:"等しい、等価の", note:"equivalence 名 等価", section:4 },
  { id:"0376", word:"mandatory", phonetic:"ˈmændətɔːri", pos:"形容詞", meaning:"強制的な、義務的な", note:"mandate 名 権限; 義務", section:4 },
  { id:"0377", word:"conventional", phonetic:"kənˈvenʃənl", pos:"形容詞", meaning:"従来の、因習的な", note:"conventional wisdom 一般通念", section:4 },
  { id:"0378", word:"constitutional", phonetic:"ˌkɒnstɪˈtjuːʃənl", pos:"形容詞", meaning:"合憲の、本国の", note:"constitution 名 憲法", section:4 },
  { id:"0379", word:"accountable", phonetic:"əˈkaʊntəbl", pos:"形容詞", meaning:"責任がある（to ~に）", note:"accountability 名 説明責任", section:4 },
  { id:"0380", word:"administrative", phonetic:"ədˈmɪnɪstrətɪv", pos:"形容詞", meaning:"行政上の、管理上の", note:"administration 名 行政、管理", section:4 },
  { id:"0381", word:"collective", phonetic:"kəˈlektɪv", pos:"形容詞", meaning:"共同の、集団の", note:"collectively 副 集合的に", section:4 },
  { id:"0382", word:"congressional", phonetic:"kənˈɡreʃənl", pos:"形容詞", meaning:"議会の、米国議会の", note:"Congress 名 米国議会", section:4 },
  { id:"0383", word:"explosive", phonetic:"ɪkˈsploʊsɪv", pos:"形容詞", meaning:"爆発的な、過激な", note:"explosion 名 爆発", section:4 },
  { id:"0384", word:"incomplete", phonetic:"ˌɪnkəmˈpliːt", pos:"形容詞", meaning:"不完全な、未完成の", note:"incompleteness 名 不完全さ", section:4 },
  { id:"0385", word:"socioeconomic", phonetic:"ˌsoʊsioʊˌiːkəˈnɒmɪk", pos:"形容詞", meaning:"社会経済的な", note:"", section:4 },
  { id:"0386", word:"territorial", phonetic:"ˌterɪˈtɔːriəl", pos:"形容詞", meaning:"領土の、縄張りを守る", note:"territorial waters 領海", section:4 },
  { id:"0387", word:"underwater", phonetic:"ˌʌndərˈwɔːtər", pos:"形容詞", meaning:"水中の、水面下の", note:"", section:4 },
  { id:"0388", word:"unrealistic", phonetic:"ˌʌnriːəˈlɪstɪk", pos:"形容詞", meaning:"非現実的な", note:"unrealistically 副 非現実的に", section:4 },
  { id:"0389", word:"negligible", phonetic:"ˈneɡlɪdʒɪbl", pos:"形容詞", meaning:"ごくわずかな、取るに足りない", note:"negligibly 副 取るに足りないほど", section:4 },
  { id:"0390", word:"overwhelming", phonetic:"ˌoʊvərˈwelmɪŋ", pos:"形容詞", meaning:"圧倒的な", note:"overwhelmingly 副 圧倒的に", section:4 },
  { id:"0391", word:"unethical", phonetic:"ʌnˈeθɪkl", pos:"形容詞", meaning:"非倫理的な", note:"unethically 副 非倫理的に", section:4 },
  { id:"0392", word:"adverse", phonetic:"ˈædvɜːrs", pos:"形容詞", meaning:"不利な、不都合な", note:"adverse effect 悪影響", section:4 },
  { id:"0393", word:"disparate", phonetic:"ˈdɪspərɪt", pos:"形容詞", meaning:"本質的に異なる", note:"disparity 名 格差", section:4 },
  { id:"0394", word:"profound", phonetic:"prəˈfaʊnd", pos:"形容詞", meaning:"深い、深遠な", note:"", section:4 },
  { id:"0395", word:"hostile", phonetic:"ˈhɒstaɪl", pos:"形容詞", meaning:"敵の、敵意のある", note:"hostility 名 敵意", section:4 },
  { id:"0396", word:"judicial", phonetic:"dʒuːˈdɪʃl", pos:"形容詞", meaning:"司法の、裁判の", note:"cf. executive 行政の; legislative 立法の", section:4 },
  // --- 副詞 ---
  { id:"0397", word:"consistently", phonetic:"kənˈsɪstəntli", pos:"副詞", meaning:"常に一貫して、安定して", note:"", section:4 },
  { id:"0398", word:"surely", phonetic:"ˈʃʊərli", pos:"副詞", meaning:"（否定文で）まさか、確かに、間違いなく", note:"≒ certainly", section:4 },
  { id:"0399", word:"subsequently", phonetic:"ˈsʌbsɪkwəntli", pos:"副詞", meaning:"その後", note:"subsequent 形 その後の", section:4 },
  { id:"0400", word:"substantially", phonetic:"səbˈstænʃəli", pos:"副詞", meaning:"かなり、相当に", note:"substantial 形 かなりの、実質的な", section:4 },

  // ===== Section 5 (0401-0500) =====
  // --- 動詞 ---
  { id:"0401", word:"divert", phonetic:"daɪˈvɜːrt", pos:"動詞", meaning:"を迂回させる、を転換させる", note:"diversion 名 迂回; 気晴らし", section:5 },
  { id:"0402", word:"uncover", phonetic:"ʌnˈkʌvər", pos:"動詞", meaning:"を暴く、を発見する", note:"≒ reveal; ≒ discover", section:5 },
  { id:"0403", word:"unearth", phonetic:"ʌnˈɜːrθ", pos:"動詞", meaning:"を発掘する", note:"≒ excavate; unearth fossils 化石を発掘する", section:5 },
  { id:"0404", word:"collaborate", phonetic:"kəˈlæbəreɪt", pos:"動詞", meaning:"協力する（with ~と）", note:"collaboration 名 協力; collaborator 協力者", section:5 },
  { id:"0405", word:"flourish", phonetic:"ˈflʌrɪʃ", pos:"動詞", meaning:"栄える", note:"≒ thrive, prosper", section:5 },
  { id:"0406", word:"certify", phonetic:"ˈsɜːrtɪfaɪ", pos:"動詞", meaning:"を認定する、を証明する", note:"certification 名 認定", section:5 },
  { id:"0407", word:"flee", phonetic:"fliː", pos:"動詞", meaning:"（から）逃げる", note:"≒ run away", section:5 },
  { id:"0408", word:"grab", phonetic:"ɡræb", pos:"動詞", meaning:"をつかむ、手に入れる", note:"≒ snatch", section:5 },
  { id:"0409", word:"revolt", phonetic:"rɪˈvoʊlt", pos:"動詞", meaning:"反乱を起こす（against ~に対して）", note:"名 反乱", section:5 },
  { id:"0410", word:"industrialize", phonetic:"ɪnˈdʌstriəlaɪz", pos:"動詞", meaning:"産業化する、工業化する", note:"industrialization 名 産業化", section:5 },
  { id:"0411", word:"rehabilitate", phonetic:"ˌriːhəˈbɪlɪteɪt", pos:"動詞", meaning:"を社会復帰させる、の名誉を回復させる", note:"rehabilitation 名 社会復帰", section:5 },
  { id:"0412", word:"repress", phonetic:"rɪˈpres", pos:"動詞", meaning:"を抑圧する、を抑制する", note:"repression 名 抑圧; repressive 形 抑圧的な", section:5 },
  { id:"0413", word:"forge", phonetic:"fɔːrdʒ", pos:"動詞", meaning:"を築き上げる、偽造する", note:"forgery 名 偽造; 偽造品", section:5 },
  { id:"0414", word:"mount", phonetic:"maʊnt", pos:"動詞", meaning:"取り付ける、に乗る、高まる", note:"", section:5 },
  { id:"0415", word:"wage", phonetic:"weɪdʒ", pos:"動詞", meaning:"を行なう", note:"wage war 戦争を行なう; 名 賃金", section:5 },
  { id:"0416", word:"prevail", phonetic:"prɪˈveɪl", pos:"動詞", meaning:"圧倒する、普及する", note:"prevailing 形 支配的な", section:5 },
  { id:"0417", word:"verify", phonetic:"ˈverɪfaɪ", pos:"動詞", meaning:"を確認する", note:"verify a fact 事実を確認する", section:5 },
  { id:"0418", word:"accelerate", phonetic:"əkˈseləreɪt", pos:"動詞", meaning:"加速させる", note:"acceleration 名 加速", section:5 },
  { id:"0419", word:"disrupt", phonetic:"dɪsˈrʌpt", pos:"動詞", meaning:"中断させる", note:"disruption 名 中断", section:5 },
  { id:"0420", word:"subordinate", phonetic:"səˈbɔːrdɪnɪt", pos:"動詞", meaning:"を下位に置く、を従属させる", note:"sub（下に）+ ordin（ランク）", section:5 },
  // --- 名詞 ---
  { id:"0421", word:"concussion", phonetic:"kənˈkʌʃən", pos:"名詞", meaning:"脳震盪", note:"brain tumor 脳腫瘍", section:5 },
  { id:"0422", word:"tumor", phonetic:"ˈtjuːmər", pos:"名詞", meaning:"腫瘍", note:"benign tumor 良性腫瘍", section:5 },
  { id:"0423", word:"irrigation", phonetic:"ˌɪrɪˈɡeɪʃən", pos:"名詞", meaning:"灌漑", note:"irrigate 動 灌漑する; irrigation canal 灌漑用水路", section:5 },
  { id:"0424", word:"bribery", phonetic:"ˈbraɪbəri", pos:"名詞", meaning:"贈賄、賄賂", note:"commit bribery 贈賄をする", section:5 },
  { id:"0425", word:"auditorium", phonetic:"ˌɔːdɪˈtɔːriəm", pos:"名詞", meaning:"公会堂、講堂", note:"≒ public hall", section:5 },
  { id:"0426", word:"niche", phonetic:"niːʃ", pos:"名詞", meaning:"適した地位、ニッチ", note:"niche analysis 市場分析", section:5 },
  { id:"0427", word:"drawback", phonetic:"ˈdrɔːbæk", pos:"名詞", meaning:"欠点、不利な点", note:"≒ shortcoming, disadvantage", section:5 },
  { id:"0428", word:"combustion", phonetic:"kəmˈbʌstʃən", pos:"名詞", meaning:"燃焼", note:"", section:5 },
  { id:"0429", word:"autism", phonetic:"ˈɔːtɪzəm", pos:"名詞", meaning:"自閉症", note:"", section:5 },
  { id:"0430", word:"acceptance", phonetic:"əkˈseptəns", pos:"名詞", meaning:"受け入れ、容認", note:"find general acceptance 一般に受け入れられる", section:5 },
  { id:"0431", word:"ammunition", phonetic:"ˌæmjʊˈnɪʃən", pos:"名詞", meaning:"弾薬、弾丸", note:"ammunition depot 弾薬庫", section:5 },
  { id:"0432", word:"artillery", phonetic:"ɑːrˈtɪləri", pos:"名詞", meaning:"大砲、砲兵隊", note:"", section:5 },
  { id:"0433", word:"carbohydrate", phonetic:"ˌkɑːrbəˈhaɪdreɪt", pos:"名詞", meaning:"炭水化物", note:"", section:5 },
  { id:"0434", word:"chain", phonetic:"tʃeɪn", pos:"名詞", meaning:"（店などの）チェーン、一続き、鎖", note:"restaurant chain レストランチェーン", section:5 },
  { id:"0435", word:"chimney", phonetic:"ˈtʃɪmni", pos:"名詞", meaning:"煙突", note:"", section:5 },
  { id:"0436", word:"coefficient", phonetic:"ˌkoʊɪˈfɪʃənt", pos:"名詞", meaning:"係数", note:"", section:5 },
  { id:"0437", word:"conception", phonetic:"kənˈsepʃən", pos:"名詞", meaning:"概念、考えつくこと、受胎", note:"conceive 動 思いつく", section:5 },
  { id:"0438", word:"congressman", phonetic:"ˈkɒŋɡresmən", pos:"名詞", meaning:"（男性の）下院議員", note:"cf. congresswoman （女性の）下院議員", section:5 },
  { id:"0439", word:"clergy", phonetic:"ˈklɜːrdʒi", pos:"名詞", meaning:"聖職者（集合的に）", note:"clergyman 名 男性聖職者", section:5 },
  { id:"0440", word:"cultivation", phonetic:"ˌkʌltɪˈveɪʃən", pos:"名詞", meaning:"耕作、栽培", note:"cultivate 動 を耕す", section:5 },
  { id:"0441", word:"dictatorship", phonetic:"dɪkˈteɪtərʃɪp", pos:"名詞", meaning:"独裁政権、独裁制", note:"dictator 名 独裁者", section:5 },
  { id:"0442", word:"diplomacy", phonetic:"dɪˈploʊməsi", pos:"名詞", meaning:"外交、外交上の手腕", note:"diplomat 名 外交官", section:5 },
  { id:"0443", word:"emergence", phonetic:"ɪˈmɜːrdʒəns", pos:"名詞", meaning:"出現", note:"emergent 形 新興の", section:5 },
  { id:"0444", word:"episode", phonetic:"ˈepɪsoʊd", pos:"名詞", meaning:"（テレビの連続物などの）1回分、挿話", note:"episodic 形 挿話的な", section:5 },
  { id:"0445", word:"fraction", phonetic:"ˈfrækʃən", pos:"名詞", meaning:"ほんの少し、分数", note:"fractional 形 断片的な", section:5 },
  { id:"0446", word:"guilt", phonetic:"ɡɪlt", pos:"名詞", meaning:"罪悪感、罪悪", note:"guilty 形 有罪の", section:5 },
  { id:"0447", word:"hatred", phonetic:"ˈheɪtrɪd", pos:"名詞", meaning:"憎悪", note:"hate 動 憎む", section:5 },
  { id:"0448", word:"hierarchy", phonetic:"ˈhaɪərɑːrki", pos:"名詞", meaning:"階層制度、ヒエラルキー", note:"hierarchical 形 階層的な", section:5 },
  { id:"0449", word:"indication", phonetic:"ˌɪndɪˈkeɪʃən", pos:"名詞", meaning:"兆し、表示", note:"indicative 形 示す", section:5 },
  { id:"0450", word:"insistence", phonetic:"ɪnˈsɪstəns", pos:"名詞", meaning:"主張、強調", note:"insistent 形 しつこい", section:5 },
  { id:"0451", word:"kitten", phonetic:"ˈkɪtən", pos:"名詞", meaning:"子猫", note:"cf. puppy 子犬", section:5 },
  { id:"0452", word:"mileage", phonetic:"ˈmaɪlɪdʒ", pos:"名詞", meaning:"走行距離、移動距離", note:"", section:5 },
  { id:"0453", word:"militia", phonetic:"mɪˈlɪʃə", pos:"名詞", meaning:"民兵（組織）", note:"militiaman 名 民兵", section:5 },
  { id:"0454", word:"missile", phonetic:"ˈmɪsaɪl", pos:"名詞", meaning:"ミサイル", note:"", section:5 },
  { id:"0455", word:"prediction", phonetic:"prɪˈdɪkʃən", pos:"名詞", meaning:"予測、予言", note:"make a correct prediction 正しい予言をする", section:5 },
  { id:"0456", word:"radar", phonetic:"ˈreɪdɑːr", pos:"名詞", meaning:"レーダー", note:"under the radar 気付かれずに", section:5 },
  { id:"0457", word:"rehabilitation", phonetic:"ˌriːhəˌbɪlɪˈteɪʃən", pos:"名詞", meaning:"社会復帰、リハビリ、復権", note:"rehabilitate 動 を更生させる", section:5 },
  { id:"0458", word:"reptile", phonetic:"ˈreptaɪl", pos:"名詞", meaning:"爬虫類", note:"reptilian 形 爬虫類の", section:5 },
  { id:"0459", word:"spectrum", phonetic:"ˈspektrəm", pos:"名詞", meaning:"（変動）範囲、スペクトル", note:"", section:5 },
  { id:"0460", word:"textile", phonetic:"ˈtekstaɪl", pos:"名詞", meaning:"繊維、布地", note:"", section:5 },
  { id:"0461", word:"transformation", phonetic:"ˌtrænsfərˈmeɪʃən", pos:"名詞", meaning:"変容、変化、変貌", note:"transform 動 を変える", section:5 },
  { id:"0462", word:"transparency", phonetic:"trænsˈpærənsi", pos:"名詞", meaning:"透明性", note:"transparent 形 透明な", section:5 },
  { id:"0463", word:"turbine", phonetic:"ˈtɜːrbaɪn", pos:"名詞", meaning:"タービン", note:"", section:5 },
  { id:"0464", word:"urbanization", phonetic:"ˌɜːrbənaɪˈzeɪʃən", pos:"名詞", meaning:"都市化", note:"urbanize 動 都市化する", section:5 },
  { id:"0465", word:"ward", phonetic:"wɔːrd", pos:"名詞", meaning:"病棟、行政区", note:"general ward 一般病棟", section:5 },
  { id:"0466", word:"gentrification", phonetic:"ˌdʒentriːfɪˈkeɪʃən", pos:"名詞", meaning:"（スラム街の）高級住宅化", note:"gentrify 動 を高級化する", section:5 },
  { id:"0467", word:"populace", phonetic:"ˈpɒpjʊləs", pos:"名詞", meaning:"大衆、庶民、全住民", note:"", section:5 },
  { id:"0468", word:"pronoun", phonetic:"ˈproʊnaʊn", pos:"名詞", meaning:"代名詞", note:"personal pronoun 人称代名詞", section:5 },
  { id:"0469", word:"heritage", phonetic:"ˈherɪtɪdʒ", pos:"名詞", meaning:"遺産", note:"inherit 動 を受け継ぐ; cultural heritage 文化遺産", section:5 },
  { id:"0470", word:"hygiene", phonetic:"ˈhaɪdʒiːn", pos:"名詞", meaning:"衛生管理、清潔", note:"hygienic 形 衛生的な; public hygiene 公衆衛生", section:5 },
  { id:"0471", word:"famine", phonetic:"ˈfæmɪn", pos:"名詞", meaning:"飢饉", note:"≒ hunger, food shortage", section:5 },
  { id:"0472", word:"conscience", phonetic:"ˈkɒnʃəns", pos:"名詞", meaning:"良心", note:"a matter of conscience 良心の問題", section:5 },
  { id:"0473", word:"specimen", phonetic:"ˈspesɪmən", pos:"名詞", meaning:"標本、見本", note:"", section:5 },
  { id:"0474", word:"preservation", phonetic:"ˌprezəˈveɪʃən", pos:"名詞", meaning:"保存、保護", note:"preserve 動 を保存する; preservative 名 防腐剤", section:5 },
  { id:"0475", word:"venue", phonetic:"ˈvenjuː", pos:"名詞", meaning:"会場、開催地", note:"", section:5 },
  // --- 形容詞 ---
  { id:"0476", word:"unprecedented", phonetic:"ʌnˈpresɪdentɪd", pos:"形容詞", meaning:"前例のない", note:"≒ unparalleled", section:5 },
  { id:"0477", word:"innate", phonetic:"ɪˈneɪt", pos:"形容詞", meaning:"生来の、固有の", note:"≒ inborn, natural; innate ability 生まれつきの能力", section:5 },
  { id:"0478", word:"staunch", phonetic:"stɔːntʃ", pos:"形容詞", meaning:"（支持・信条が）強固な", note:"", section:5 },
  { id:"0479", word:"agrarian", phonetic:"əˈɡreəriən", pos:"形容詞", meaning:"農地の、農業の", note:"", section:5 },
  { id:"0480", word:"juvenile", phonetic:"ˈdʒuːvənaɪl", pos:"形容詞", meaning:"青少年の、（比喩的に）幼稚な", note:"", section:5 },
  { id:"0481", word:"cautious", phonetic:"ˈkɔːʃəs", pos:"形容詞", meaning:"慎重な", note:"caution 名 注意", section:5 },
  { id:"0482", word:"charitable", phonetic:"ˈtʃærɪtəbl", pos:"形容詞", meaning:"慈善的な", note:"charity 名 慈善（団体）", section:5 },
  { id:"0483", word:"evident", phonetic:"ˈevɪdənt", pos:"形容詞", meaning:"明白な", note:"evidence 名 証拠", section:5 },
  { id:"0484", word:"hazardous", phonetic:"ˈhæzərdəs", pos:"形容詞", meaning:"危険な", note:"hazard 名 危険要因", section:5 },
  { id:"0485", word:"progressive", phonetic:"prəˈɡresɪv", pos:"形容詞", meaning:"進歩的な", note:"progress 名 進歩", section:5 },
  { id:"0486", word:"revolutionary", phonetic:"ˌrevəˈluːʃəneri", pos:"形容詞", meaning:"革命的な", note:"revolution 名 革命", section:5 },
  { id:"0487", word:"complimentary", phonetic:"ˌkɒmplɪˈmentəri", pos:"形容詞", meaning:"無料の、賛辞の", note:"compliment 名 お世辞", section:5 },
  { id:"0488", word:"convincing", phonetic:"kənˈvɪnsɪŋ", pos:"形容詞", meaning:"説得力のある", note:"convincingly 副 説得力を持って", section:5 },
  { id:"0489", word:"depressed", phonetic:"dɪˈprest", pos:"形容詞", meaning:"ふさぎ込んだ、うつ病の", note:"depression 名 うつ病", section:5 },
  { id:"0490", word:"Paleolithic", phonetic:"ˌpeɪliəˈlɪθɪk", pos:"形容詞", meaning:"旧石器時代の", note:"≒ Neolithic 新石器時代の", section:5 },
  { id:"0491", word:"Protestant", phonetic:"ˈprɒtɪstənt", pos:"形容詞", meaning:"プロテスタントの、新教の", note:"Protestantism 名 新教", section:5 },
  { id:"0492", word:"real-life", phonetic:"ˌriːlˈlaɪf", pos:"形容詞", meaning:"現実の、実際の", note:"⇔ fictional 架空の", section:5 },
  { id:"0493", word:"comprehensive", phonetic:"ˌkɒmprɪˈhensɪv", pos:"形容詞", meaning:"総合的な、包括的な", note:"comprehensive insurance 総合保険", section:5 },
  { id:"0494", word:"anonymous", phonetic:"əˈnɒnɪməs", pos:"形容詞", meaning:"作者不詳の、匿名の", note:"anonymously 副 匿名で", section:5 },
  { id:"0495", word:"indispensable", phonetic:"ˌɪndɪˈspensəbl", pos:"形容詞", meaning:"必要不可欠な", note:"≒ essential", section:5 },
  { id:"0496", word:"transparent", phonetic:"trænsˈpærənt", pos:"形容詞", meaning:"透明な、明瞭な", note:"transparency 名 透明性", section:5 },
  { id:"0497", word:"diverse", phonetic:"daɪˈvɜːrs", pos:"形容詞", meaning:"多様な", note:"diversify 動 多様化する; diversity 名 多様性", section:5 },
  // --- 副詞 ---
  { id:"0498", word:"overly", phonetic:"ˈoʊvərli", pos:"副詞", meaning:"過度に", note:"≒ excessively", section:5 },
  { id:"0499", word:"internationally", phonetic:"ˌɪntərˈnæʃənəli", pos:"副詞", meaning:"国際的に", note:"", section:5 },
  { id:"0500", word:"mistakenly", phonetic:"mɪˈsteɪkənli", pos:"副詞", meaning:"誤って、間違って", note:"≒ by mistake", section:5 },

  // ===== Section 6 (0501-0600) =====
  // --- 動詞 ---
  { id:"0501", word:"resent", phonetic:"rɪˈzent", pos:"動詞", meaning:"に憤る、を憤慨する", note:"resentment 名 憤り", section:6 },
  { id:"0502", word:"devastate", phonetic:"ˈdevəsteɪt", pos:"動詞", meaning:"を壊滅させる", note:"≒ destroy", section:6 },
  { id:"0503", word:"provoke", phonetic:"prəˈvoʊk", pos:"動詞", meaning:"を引き起こす、を怒らせる", note:"provocation 名 挑発", section:6 },
  { id:"0504", word:"hedge", phonetic:"hedʒ", pos:"動詞", meaning:"生垣で囲む、言質を与えないようにする", note:"名 生垣", section:6 },
  { id:"0505", word:"enlighten", phonetic:"ɪnˈlaɪtən", pos:"動詞", meaning:"に教える、を啓発する", note:"enlightenment 名 啓発", section:6 },
  { id:"0506", word:"emulate", phonetic:"ˈemjʊleɪt", pos:"動詞", meaning:"を模倣する", note:"emulation 名 模倣", section:6 },
  { id:"0507", word:"denounce", phonetic:"dɪˈnaʊns", pos:"動詞", meaning:"を公然と非難する", note:"denunciation 名 非難", section:6 },
  { id:"0508", word:"disperse", phonetic:"dɪˈspɜːrs", pos:"動詞", meaning:"分散する、解散させる", note:"dispersal 名 分散", section:6 },
  { id:"0509", word:"alienate", phonetic:"ˈeɪliəneɪt", pos:"動詞", meaning:"を遠ざける", note:"alienation 名 疎外; cf. alien 外国人", section:6 },
  { id:"0510", word:"squander", phonetic:"ˈskwɒndər", pos:"動詞", meaning:"を浪費する", note:"≒ lavish, waste", section:6 },
  { id:"0511", word:"discard", phonetic:"dɪˈskɑːrd", pos:"動詞", meaning:"を捨てる", note:"≒ dump, throw away", section:6 },
  { id:"0512", word:"hamper", phonetic:"ˈhæmpər", pos:"動詞", meaning:"を妨げる", note:"≒ hinder, impede, prevent", section:6 },
  { id:"0513", word:"waive", phonetic:"weɪv", pos:"動詞", meaning:"を放棄する", note:"≒ relinquish, forgo; waiver 名 権利放棄", section:6 },
  { id:"0514", word:"defy", phonetic:"dɪˈfaɪ", pos:"動詞", meaning:"に反抗する", note:"≒ disobey; defiance 名 反抗", section:6 },
  { id:"0515", word:"ambush", phonetic:"ˈæmbʊʃ", pos:"動詞", meaning:"を待ち伏せして襲う", note:"名 待ち伏せ", section:6 },
  { id:"0516", word:"obliterate", phonetic:"əˈblɪtəreɪt", pos:"動詞", meaning:"を消滅させる", note:"", section:6 },
  { id:"0517", word:"secede", phonetic:"sɪˈsiːd", pos:"動詞", meaning:"脱退する、分離独立する", note:"secession 名 脱退", section:6 },
  { id:"0518", word:"slash", phonetic:"slæʃ", pos:"動詞", meaning:"大幅に削減する", note:"≒ reduce greatly", section:6 },
  { id:"0519", word:"mutate", phonetic:"mjuːˈteɪt", pos:"動詞", meaning:"変異する", note:"mutation 名 突然変異", section:6 },
  { id:"0520", word:"decimate", phonetic:"ˈdesɪmeɪt", pos:"動詞", meaning:"大量に減少させる", note:"", section:6 },
  { id:"0521", word:"condemn", phonetic:"kənˈdem", pos:"動詞", meaning:"を厳しく非難する", note:"condemnation 名 非難", section:6 },
  { id:"0522", word:"correlate", phonetic:"ˈkɒrəleɪt", pos:"動詞", meaning:"互いに関連させる（with ~と）", note:"correlation 名 相関関係", section:6 },
  { id:"0523", word:"descend", phonetic:"dɪˈsend", pos:"動詞", meaning:"を下る、血統が属する", note:"descendant 名 子孫", section:6 },
  { id:"0524", word:"imprison", phonetic:"ɪmˈprɪzən", pos:"動詞", meaning:"を投獄する", note:"imprisonment 名 投獄", section:6 },
  { id:"0525", word:"inflict", phonetic:"ɪnˈflɪkt", pos:"動詞", meaning:"（苦痛など）を与える（on ~に）", note:"infliction 名 苦痛を与えること", section:6 },
  { id:"0526", word:"rally", phonetic:"ˈræli", pos:"動詞", meaning:"を結集させる、集結する", note:"名 大集会", section:6 },
  { id:"0527", word:"reassure", phonetic:"ˌriːəˈʃʊər", pos:"動詞", meaning:"を安心させる", note:"reassurance 名 再保証", section:6 },
  { id:"0528", word:"scalp", phonetic:"skælp", pos:"動詞", meaning:"（チケットなど）をダフ屋する", note:"scalper 名 ダフ屋", section:6 },
  // --- 名詞 ---
  { id:"0529", word:"ratio", phonetic:"ˈreɪʃioʊ", pos:"名詞", meaning:"比率、割合", note:"in the ratio of 5 to 2 5対2の割合で", section:6 },
  { id:"0530", word:"patent", phonetic:"ˈpeɪtənt", pos:"名詞", meaning:"特許（権）、専売特許", note:"apply for a patent 特許を申請する", section:6 },
  { id:"0531", word:"fraud", phonetic:"frɔːd", pos:"名詞", meaning:"詐欺", note:"real-estate fraud 不動産詐欺", section:6 },
  { id:"0532", word:"massacre", phonetic:"ˈmæsəkər", pos:"名詞", meaning:"大量虐殺", note:"≒ slaughter", section:6 },
  { id:"0533", word:"credibility", phonetic:"ˌkredɪˈbɪlɪti", pos:"名詞", meaning:"信頼性、確実性", note:"credible 形 信頼できる", section:6 },
  { id:"0534", word:"demise", phonetic:"dɪˈmaɪz", pos:"名詞", meaning:"死去、終焉", note:"", section:6 },
  { id:"0535", word:"clout", phonetic:"klaʊt", pos:"名詞", meaning:"影響力、勢力", note:"", section:6 },
  { id:"0536", word:"resurgence", phonetic:"rɪˈsɜːrdʒəns", pos:"名詞", meaning:"復活、再起", note:"≒ revival, comeback", section:6 },
  { id:"0537", word:"cortex", phonetic:"ˈkɔːrteks", pos:"名詞", meaning:"大脳皮質", note:"", section:6 },
  { id:"0538", word:"cognition", phonetic:"kɒɡˈnɪʃən", pos:"名詞", meaning:"認知、認識", note:"cognitive 形 認知の", section:6 },
  { id:"0539", word:"accountability", phonetic:"əˌkaʊntəˈbɪlɪti", pos:"名詞", meaning:"説明責任、責任", note:"accountable 形 責任がある", section:6 },
  { id:"0540", word:"acquisition", phonetic:"ˌækwɪˈzɪʃən", pos:"名詞", meaning:"習得、合併、取得", note:"mergers and acquisitions 合併買収", section:6 },
  { id:"0541", word:"acre", phonetic:"ˈeɪkər", pos:"名詞", meaning:"エーカー（≒ 0.4ヘクタール）", note:"", section:6 },
  { id:"0542", word:"aggression", phonetic:"əˈɡreʃən", pos:"名詞", meaning:"攻撃性", note:"aggressive 形 攻撃的な", section:6 },
  { id:"0543", word:"assertion", phonetic:"əˈsɜːrʃən", pos:"名詞", meaning:"主張、断言", note:"assertive 形 積極的な", section:6 },
  { id:"0544", word:"authenticity", phonetic:"ˌɔːθenˈtɪsɪti", pos:"名詞", meaning:"真実性、信ぴょう性", note:"authentic 形 本物の", section:6 },
  { id:"0545", word:"booth", phonetic:"buːθ", pos:"名詞", meaning:"ブース、仕切り席", note:"information booth 案内所", section:6 },
  { id:"0546", word:"broadcaster", phonetic:"ˈbrɔːdkɑːstər", pos:"名詞", meaning:"放送局員、キャスター", note:"", section:6 },
  { id:"0547", word:"bud", phonetic:"bʌd", pos:"名詞", meaning:"芽、つぼみ", note:"", section:6 },
  { id:"0548", word:"canopy", phonetic:"ˈkænəpi", pos:"名詞", meaning:"（森林を覆う）林冠、天蓋", note:"", section:6 },
  { id:"0549", word:"carriage", phonetic:"ˈkærɪdʒ", pos:"名詞", meaning:"（4輪の）馬車、乳母車、客車", note:"", section:6 },
  { id:"0550", word:"clash", phonetic:"klæʃ", pos:"名詞", meaning:"衝突、小競り合い", note:"", section:6 },
  { id:"0551", word:"complexity", phonetic:"kəmˈpleksɪti", pos:"名詞", meaning:"複雑さ", note:"complex 形 複雑な", section:6 },
  { id:"0552", word:"consciousness", phonetic:"ˈkɒnʃəsnəs", pos:"名詞", meaning:"意識、自覚、認識", note:"conscious 形 意識している", section:6 },
  { id:"0553", word:"deception", phonetic:"dɪˈsepʃən", pos:"名詞", meaning:"欺瞞、ごまかし", note:"deceptive 形 人を欺く", section:6 },
  { id:"0554", word:"defendant", phonetic:"dɪˈfendənt", pos:"名詞", meaning:"被告", note:"≒ plaintiff 原告", section:6 },
  { id:"0555", word:"diplomat", phonetic:"ˈdɪpləmæt", pos:"名詞", meaning:"外交官", note:"", section:6 },
  { id:"0556", word:"fluctuation", phonetic:"ˌflʌktʃuˈeɪʃən", pos:"名詞", meaning:"変動、不規則な変化", note:"fluctuate 動 変動する", section:6 },
  { id:"0557", word:"governor", phonetic:"ˈɡʌvənər", pos:"名詞", meaning:"知事、統治者", note:"", section:6 },
  { id:"0558", word:"guerrilla", phonetic:"ɡəˈrɪlə", pos:"名詞", meaning:"ゲリラ", note:"guerrilla warfare ゲリラ戦", section:6 },
  { id:"0559", word:"honesty", phonetic:"ˈɒnɪsti", pos:"名詞", meaning:"誠実さ、正直", note:"honest 形 誠実な", section:6 },
  { id:"0560", word:"inheritance", phonetic:"ɪnˈherɪtəns", pos:"名詞", meaning:"遺産、相続", note:"inherit 動 を相続する", section:6 },
  { id:"0561", word:"injustice", phonetic:"ɪnˈdʒʌstɪs", pos:"名詞", meaning:"不公正、不公平", note:"⇔ justice 公正", section:6 },
  { id:"0562", word:"lag", phonetic:"læɡ", pos:"名詞", meaning:"遅れ、すれ", note:"", section:6 },
  { id:"0563", word:"linguistics", phonetic:"lɪŋˈɡwɪstɪks", pos:"名詞", meaning:"言語学", note:"linguistic 形 言語の", section:6 },
  { id:"0564", word:"margin", phonetic:"ˈmɑːrdʒɪn", pos:"名詞", meaning:"（勝敗などの）差、利ざや、余白", note:"by a large margin 大差で", section:6 },
  { id:"0565", word:"optimism", phonetic:"ˈɒptɪmɪzəm", pos:"名詞", meaning:"楽観主義", note:"optimist 名 楽観主義者; optimistic 形 楽観的な", section:6 },
  { id:"0566", word:"parliament", phonetic:"ˈpɑːrləmənt", pos:"名詞", meaning:"（英国の）議会、国会", note:"parliamentary 形 議会の", section:6 },
  { id:"0567", word:"policymaker", phonetic:"ˈpɒlɪsiˌmeɪkər", pos:"名詞", meaning:"政策立案者", note:"", section:6 },
  { id:"0568", word:"pollen", phonetic:"ˈpɒlən", pos:"名詞", meaning:"花粉", note:"cf. hay fever 花粉症", section:6 },
  { id:"0569", word:"reconstruction", phonetic:"ˌriːkənˈstrʌkʃən", pos:"名詞", meaning:"（南北戦争後の）再建、復旧", note:"reconstruct 動 を復元する", section:6 },
  { id:"0570", word:"relocation", phonetic:"ˌriːloʊˈkeɪʃən", pos:"名詞", meaning:"移転、移動", note:"relocate 動 を移転させる", section:6 },
  // --- 形容詞 ---
  { id:"0571", word:"plausible", phonetic:"ˈplɔːzɪbl", pos:"形容詞", meaning:"もっともらしい", note:"plausible argument 論に合った議論", section:6 },
  { id:"0572", word:"irrelevant", phonetic:"ɪˈreləvənt", pos:"形容詞", meaning:"不適切な、無関係な", note:"irrelevance 名 無関係", section:6 },
  { id:"0573", word:"ongoing", phonetic:"ˈɒnɡoʊɪŋ", pos:"形容詞", meaning:"継続（進行）中の", note:"ongoing negotiations 進行中の交渉", section:6 },
  { id:"0574", word:"potent", phonetic:"ˈpoʊtənt", pos:"形容詞", meaning:"強力な", note:"potency 名 強さ、効力", section:6 },
  { id:"0575", word:"intact", phonetic:"ɪnˈtækt", pos:"形容詞", meaning:"損なわれていない、元の通りの", note:"", section:6 },
  { id:"0576", word:"identical", phonetic:"aɪˈdentɪkl", pos:"形容詞", meaning:"全く同じ", note:"be identical in size 大きさがまったく同じ", section:6 },
  { id:"0577", word:"paramount", phonetic:"ˈpærəmaʊnt", pos:"形容詞", meaning:"最重要の", note:"", section:6 },
  { id:"0578", word:"detrimental", phonetic:"ˌdetrɪˈmentl", pos:"形容詞", meaning:"有害な", note:"detriment 名 損害", section:6 },
  { id:"0579", word:"gullible", phonetic:"ˈɡʌlɪbl", pos:"形容詞", meaning:"だまされやすい", note:"gullibility 名 だまされやすさ", section:6 },
  { id:"0580", word:"integral", phonetic:"ˈɪntɪɡrəl", pos:"形容詞", meaning:"不可欠な、完全な", note:"≒ essential; ≒ perfect", section:6 },
  { id:"0581", word:"outright", phonetic:"ˈaʊtraɪt", pos:"形容詞", meaning:"完全な、率直な", note:"outright refusal 完全な拒否", section:6 },
  { id:"0582", word:"feasible", phonetic:"ˈfiːzɪbl", pos:"形容詞", meaning:"実行可能な", note:"feasible goal 実行可能な目標", section:6 },
  { id:"0583", word:"vicious", phonetic:"ˈvɪʃəs", pos:"形容詞", meaning:"残酷な、悪意のある", note:"≒ brutal, malicious", section:6 },
  { id:"0584", word:"lethal", phonetic:"ˈliːθl", pos:"形容詞", meaning:"致命的な", note:"lethal injury 致命傷", section:6 },
  { id:"0585", word:"neural", phonetic:"ˈnjʊərəl", pos:"形容詞", meaning:"神経の", note:"neural cell 神経細胞", section:6 },
  { id:"0586", word:"mundane", phonetic:"mʌnˈdeɪn", pos:"形容詞", meaning:"ありきたりの、世俗的な", note:"", section:6 },
  { id:"0587", word:"climatic", phonetic:"klaɪˈmætɪk", pos:"形容詞", meaning:"気候の", note:"climatic change 気候変動", section:6 },
  { id:"0588", word:"facial", phonetic:"ˈfeɪʃl", pos:"形容詞", meaning:"顔の", note:"", section:6 },
  { id:"0589", word:"humanitarian", phonetic:"hjuːˌmænɪˈteəriən", pos:"形容詞", meaning:"人道主義的な", note:"humanitarian aid 人道支援", section:6 },
  { id:"0590", word:"incompetent", phonetic:"ɪnˈkɒmpɪtənt", pos:"形容詞", meaning:"無能な", note:"incompetence 名 無能", section:6 },
  { id:"0591", word:"insane", phonetic:"ɪnˈseɪn", pos:"形容詞", meaning:"頭がおかしい、正気でない", note:"insanity 名 精神異常", section:6 },
  { id:"0592", word:"microscopic", phonetic:"ˌmaɪkrəˈskɒpɪk", pos:"形容詞", meaning:"顕微鏡でしか見えない、極微の", note:"microscopically 副 顕微鏡を使って", section:6 },
  { id:"0593", word:"missionary", phonetic:"ˈmɪʃəneri", pos:"形容詞", meaning:"伝道の、布教の", note:"名 宣教師", section:6 },
  { id:"0594", word:"monetary", phonetic:"ˈmʌnɪteri", pos:"形容詞", meaning:"金融の、通貨の", note:"monetary crisis 通貨危機", section:6 },
  { id:"0595", word:"physiological", phonetic:"ˌfɪziəˈlɒdʒɪkl", pos:"形容詞", meaning:"生理学的な", note:"physiologist 名 生理学者", section:6 },
  { id:"0596", word:"privileged", phonetic:"ˈprɪvɪlɪdʒd", pos:"形容詞", meaning:"特権のある、特権階級の", note:"the privileged 特権階級の人々", section:6 },
  // --- 副詞 ---
  { id:"0597", word:"aggressively", phonetic:"əˈɡresɪvli", pos:"副詞", meaning:"積極的に、意欲的に、攻撃的に", note:"", section:6 },
  { id:"0598", word:"considerably", phonetic:"kənˈsɪdərəbli", pos:"副詞", meaning:"かなり、相当に", note:"considerable 形 かなりの", section:6 },
  { id:"0599", word:"exclusively", phonetic:"ɪkˈskluːsɪvli", pos:"副詞", meaning:"もっぱら、独占的に", note:"", section:6 },
  { id:"0600", word:"readily", phonetic:"ˈredɪli", pos:"副詞", meaning:"たやすく、喜んで", note:"", section:6 },

  // ===== Section 7 (0601-0700) =====
  // --- 動詞 ---
  { id:"0601", word:"spark", phonetic:"spɑːrk", pos:"動詞", meaning:"を引き起こす", note:"≒ provoke, trigger; 名 火花", section:7 },
  { id:"0602", word:"escalate", phonetic:"ˈeskəleɪt", pos:"動詞", meaning:"エスカレートする", note:"escalation 名 段階的な拡大", section:7 },
  { id:"0603", word:"obsess", phonetic:"əbˈses", pos:"動詞", meaning:"に取りつかれる（with ~に）", note:"obsession 名 執着", section:7 },
  { id:"0604", word:"reel", phonetic:"riːl", pos:"動詞", meaning:"動揺する、よろける", note:"名 リール", section:7 },
  { id:"0605", word:"refill", phonetic:"ˌriːˈfɪl", pos:"動詞", meaning:"を再び満たす", note:"名 詰め替え用品", section:7 },
  { id:"0606", word:"outnumber", phonetic:"ˌaʊtˈnʌmbər", pos:"動詞", meaning:"より数で勝る", note:"", section:7 },
  { id:"0607", word:"eclipse", phonetic:"ɪˈklɪps", pos:"動詞", meaning:"を凌ぐ、を覆い隠す", note:"≒ surpass; 名 食（月食・日食）", section:7 },
  { id:"0608", word:"hatch", phonetic:"hætʃ", pos:"動詞", meaning:"（卵が）孵化する", note:"hatch eggs 卵をかえす", section:7 },
  { id:"0609", word:"thrive", phonetic:"θraɪv", pos:"動詞", meaning:"繁栄する、栄える", note:"≒ be successful; ⇔ decline 衰える", section:7 },
  { id:"0610", word:"contaminate", phonetic:"kənˈtæmɪneɪt", pos:"動詞", meaning:"を汚染する", note:"contamination 名 汚染", section:7 },
  { id:"0611", word:"displace", phonetic:"dɪsˈpleɪs", pos:"動詞", meaning:"を強制退去させる、を移動させる", note:"displacement 名 強制移住", section:7 },
  { id:"0612", word:"precede", phonetic:"prɪˈsiːd", pos:"動詞", meaning:"に先んじる", note:"precedence 名 先行; precedent 名 前例", section:7 },
  { id:"0613", word:"prescribe", phonetic:"prɪˈskraɪb", pos:"動詞", meaning:"を規定する、を処方する", note:"prescription 名 処方箋", section:7 },
  { id:"0614", word:"subsidize", phonetic:"ˈsʌbsɪdaɪz", pos:"動詞", meaning:"を補助金で支援する", note:"subsidy 名 補助金", section:7 },
  { id:"0615", word:"amend", phonetic:"əˈmend", pos:"動詞", meaning:"（法律など）を修正する、を改正する", note:"amendment 名 修正", section:7 },
  { id:"0616", word:"replicate", phonetic:"ˈreplɪkeɪt", pos:"動詞", meaning:"を複製する", note:"≒ duplicate; replica 名 複製品", section:7 },
  { id:"0617", word:"deteriorate", phonetic:"dɪˈtɪəriəreɪt", pos:"動詞", meaning:"悪化する", note:"deterioration 名 悪化", section:7 },
  { id:"0618", word:"hinder", phonetic:"ˈhɪndər", pos:"動詞", meaning:"を妨げる", note:"≒ hamper; hindrance 名 妨げ", section:7 },
  { id:"0619", word:"excel", phonetic:"ɪkˈsel", pos:"動詞", meaning:"に優れる（in ~に）、に勝る", note:"excellence 名 優秀さ", section:7 },
  { id:"0620", word:"exert", phonetic:"ɪɡˈzɜːrt", pos:"動詞", meaning:"を行使する、を発揮する", note:"exert all one's strength 全力を尽くす", section:7 },
  { id:"0621", word:"concede", phonetic:"kənˈsiːd", pos:"動詞", meaning:"（仕方なく）認める", note:"concession 名 譲歩", section:7 },
  { id:"0622", word:"spur", phonetic:"spɜːr", pos:"動詞", meaning:"を刺激する（to do ~するように）", note:"≒ encourage; 名 拍車", section:7 },
  { id:"0623", word:"exacerbate", phonetic:"ɪɡˈzæsəbeɪt", pos:"動詞", meaning:"を悪化させる", note:"≒ aggravate", section:7 },
  { id:"0624", word:"invoke", phonetic:"ɪnˈvoʊk", pos:"動詞", meaning:"（権威など）を持ち出す、（法などを）発動させる", note:"", section:7 },
  { id:"0625", word:"encompass", phonetic:"ɪnˈkʌmpəs", pos:"動詞", meaning:"を取り囲む、を含む", note:"≒ encircle", section:7 },
  { id:"0626", word:"evaporate", phonetic:"ɪˈvæpəreɪt", pos:"動詞", meaning:"蒸発する", note:"evaporation 名 蒸発", section:7 },
  { id:"0627", word:"override", phonetic:"ˌoʊvərˈraɪd", pos:"動詞", meaning:"を覆す、より優先的に立つ", note:"", section:7 },
  // --- 名詞 ---
  { id:"0628", word:"renovation", phonetic:"ˌrenəˈveɪʃən", pos:"名詞", meaning:"改修、改装", note:"extensive home renovation 家の大規模リフォーム", section:7 },
  { id:"0629", word:"repression", phonetic:"rɪˈpreʃən", pos:"名詞", meaning:"弾圧", note:"≒ oppression, suppression; repressive 形 抑圧的な", section:7 },
  { id:"0630", word:"revision", phonetic:"rɪˈvɪʒən", pos:"名詞", meaning:"変更、改正、改訂", note:"revise 動 を修正する", section:7 },
  { id:"0631", word:"scarcity", phonetic:"ˈskɑːrsɪti", pos:"名詞", meaning:"欠乏、不足", note:"scarce 形 乏しい", section:7 },
  { id:"0632", word:"scenario", phonetic:"sɪˈnɑːrioʊ", pos:"名詞", meaning:"予想事態、シナリオ", note:"", section:7 },
  { id:"0633", word:"scope", phonetic:"skoʊp", pos:"名詞", meaning:"範囲、余地", note:"beyond the scope of 〜の範囲を超えて", section:7 },
  { id:"0634", word:"sponsorship", phonetic:"ˈspɒnsərʃɪp", pos:"名詞", meaning:"スポンサーであること、後援", note:"", section:7 },
  { id:"0635", word:"subsidy", phonetic:"ˈsʌbsɪdi", pos:"名詞", meaning:"補助金、助成金", note:"housing subsidy 住宅補助金", section:7 },
  { id:"0636", word:"tank", phonetic:"tæŋk", pos:"名詞", meaning:"タンク、戦車", note:"water tank 水槽", section:7 },
  { id:"0637", word:"taxpayer", phonetic:"ˈtækspeiər", pos:"名詞", meaning:"納税者", note:"", section:7 },
  { id:"0638", word:"terror", phonetic:"ˈterər", pos:"名詞", meaning:"テロ（行為）、恐怖", note:"≒ terrorism, horror", section:7 },
  { id:"0639", word:"transition", phonetic:"trænˈzɪʃən", pos:"名詞", meaning:"移行、移り変わり", note:"transitional 形 移行期の", section:7 },
  { id:"0640", word:"acidification", phonetic:"əˌsɪdɪfɪˈkeɪʃən", pos:"名詞", meaning:"酸化", note:"", section:7 },
  { id:"0641", word:"clone", phonetic:"kloʊn", pos:"名詞", meaning:"クローン", note:"クローンを作る", section:7 },
  { id:"0642", word:"geneticist", phonetic:"dʒɪˈnetɪsɪst", pos:"名詞", meaning:"遺伝学者", note:"genetics 名 遺伝学", section:7 },
  { id:"0643", word:"logistics", phonetic:"ləˈdʒɪstɪks", pos:"名詞", meaning:"物流、兵站の詳細な計画", note:"", section:7 },
  { id:"0644", word:"nanotechnology", phonetic:"ˌnænoʊtekˈnɒlədʒi", pos:"名詞", meaning:"ナノテクノロジー", note:"", section:7 },
  { id:"0645", word:"orphan", phonetic:"ˈɔːrfən", pos:"名詞", meaning:"孤児", note:"orphanage 名 孤児院", section:7 },
  { id:"0646", word:"photosynthesis", phonetic:"ˌfoʊtəˈsɪnθɪsɪs", pos:"名詞", meaning:"光合成", note:"", section:7 },
  { id:"0647", word:"proclamation", phonetic:"ˌprɒkləˈmeɪʃən", pos:"名詞", meaning:"宣言、公告", note:"proclaim 動 を宣言する", section:7 },
  { id:"0648", word:"reimbursement", phonetic:"ˌriːɪmˈbɜːrsmənt", pos:"名詞", meaning:"払い戻し、償還", note:"reimburse 動 を払い戻す", section:7 },
  { id:"0649", word:"subtitle", phonetic:"ˈsʌbtaɪtl", pos:"名詞", meaning:"（外国映画などの）字幕、副題", note:"", section:7 },
  { id:"0650", word:"surcharge", phonetic:"ˈsɜːrtʃɑːrdʒ", pos:"名詞", meaning:"サーチャージ、追加料金", note:"", section:7 },
  { id:"0651", word:"trade-off", phonetic:"ˈtreɪdɒf", pos:"名詞", meaning:"トレードオフ（between ~の間の）", note:"≒ 二者いずれかのバランスをとること", section:7 },
  { id:"0652", word:"vocalization", phonetic:"ˌvoʊkəlaɪˈzeɪʃən", pos:"名詞", meaning:"発声した音", note:"", section:7 },
  { id:"0653", word:"x-ray", phonetic:"ˈeksreɪ", pos:"名詞", meaning:"エックス線写真、レントゲン写真", note:"形 エックス線の", section:7 },
  { id:"0654", word:"contradiction", phonetic:"ˌkɒntrəˈdɪkʃən", pos:"名詞", meaning:"矛盾", note:"contradictory 形 矛盾した", section:7 },
  { id:"0655", word:"recession", phonetic:"rɪˈseʃən", pos:"名詞", meaning:"不況（景気後退）", note:"", section:7 },
  { id:"0656", word:"immunity", phonetic:"ɪˈmjuːnɪti", pos:"名詞", meaning:"免疫", note:"immune 形 免疫がある", section:7 },
  { id:"0657", word:"array", phonetic:"əˈreɪ", pos:"名詞", meaning:"配列、ずらりと並んだもの", note:"", section:7 },
  { id:"0658", word:"latitude", phonetic:"ˈlætɪtjuːd", pos:"名詞", meaning:"緯度", note:"cf. longitude 経度", section:7 },
  { id:"0659", word:"gravity", phonetic:"ˈɡrævɪti", pos:"名詞", meaning:"重力、引力、重大さ", note:"", section:7 },
  { id:"0660", word:"prestige", phonetic:"preˈstiːʒ", pos:"名詞", meaning:"名声、威信", note:"prestigious 形 名声のある", section:7 },
  { id:"0661", word:"coincidence", phonetic:"koʊˈɪnsɪdəns", pos:"名詞", meaning:"偶然、偶然の一致", note:"coincide 動 一致する", section:7 },
  { id:"0662", word:"intake", phonetic:"ˈɪnteɪk", pos:"名詞", meaning:"入学者数、摂取量", note:"", section:7 },
  { id:"0663", word:"surplus", phonetic:"ˈsɜːrpləs", pos:"名詞", meaning:"余剰、余分", note:"⇔ deficit 赤字", section:7 },
  { id:"0664", word:"bibliography", phonetic:"ˌbɪbliˈɒɡrəfi", pos:"名詞", meaning:"参考文献目録", note:"", section:7 },
  { id:"0665", word:"ballot", phonetic:"ˈbælət", pos:"名詞", meaning:"投票、投票用紙", note:"cast a ballot 投票する", section:7 },
  { id:"0666", word:"outrage", phonetic:"ˈaʊtreɪdʒ", pos:"名詞", meaning:"激怒、憤慨", note:"outrageous 形 とんでもない", section:7 },
  { id:"0667", word:"juror", phonetic:"ˈdʒʊərər", pos:"名詞", meaning:"陪審員", note:"cf. jury 名 陪審員団", section:7 },
  { id:"0668", word:"restoration", phonetic:"ˌrestəˈreɪʃən", pos:"名詞", meaning:"修復、復旧", note:"restore 動 を修復する", section:7 },
  { id:"0669", word:"conversion", phonetic:"kənˈvɜːrʒən", pos:"名詞", meaning:"転換、改宗", note:"convert 動 を転換する", section:7 },
  { id:"0670", word:"autonomy", phonetic:"ɔːˈtɒnəmi", pos:"名詞", meaning:"自治（権）、自律性", note:"autonomous 形 自治の", section:7 },
  { id:"0671", word:"onset", phonetic:"ˈɒnset", pos:"名詞", meaning:"（特に好ましくないことの）始まり、発症", note:"the onset of a disease 発病", section:7 },
  { id:"0672", word:"disparity", phonetic:"dɪˈspærɪti", pos:"名詞", meaning:"相違、格差", note:"disparate 形 大きく異なる", section:7 },
  { id:"0673", word:"devastation", phonetic:"ˌdevəˈsteɪʃən", pos:"名詞", meaning:"壊滅、荒廃", note:"devastate 動 を壊滅させる", section:7 },
  { id:"0674", word:"havoc", phonetic:"ˈhævək", pos:"名詞", meaning:"大混乱、破壊", note:"play havoc with 〜をめちゃくちゃにする", section:7 },
  // --- 形容詞 ---
  { id:"0675", word:"spectacular", phonetic:"spekˈtækjʊlər", pos:"形容詞", meaning:"壮観な、華やかな", note:"spectacularly 副 壮観に", section:7 },
  { id:"0676", word:"unintended", phonetic:"ˌʌnɪnˈtendɪd", pos:"形容詞", meaning:"予定外の、意図しない", note:"", section:7 },
  { id:"0677", word:"antiwar", phonetic:"ˌæntiˈwɔːr", pos:"形容詞", meaning:"反戦の", note:"antiwar movement 反戦運動", section:7 },
  { id:"0678", word:"entrenched", phonetic:"ɪnˈtrentʃt", pos:"形容詞", meaning:"強固に根付いた、確立した", note:"entrenchment 名 定着", section:7 },
  { id:"0679", word:"high-intensity", phonetic:"haɪ ɪnˈtensɪti", pos:"形容詞", meaning:"高強度の", note:"", section:7 },
  { id:"0680", word:"lasting", phonetic:"ˈlɑːstɪŋ", pos:"形容詞", meaning:"永続的な、長続きする", note:"lastingly 副 永久に", section:7 },
  { id:"0681", word:"prehistoric", phonetic:"ˌpriːhɪˈstɒrɪk", pos:"形容詞", meaning:"先史時代の", note:"prehistory 名 先史時代", section:7 },
  { id:"0682", word:"staggering", phonetic:"ˈstæɡərɪŋ", pos:"形容詞", meaning:"驚異的な、圧倒的な", note:"staggeringly 副 驚くほど", section:7 },
  { id:"0683", word:"transgender", phonetic:"trænzˈdʒendər", pos:"形容詞", meaning:"トランスジェンダーの", note:"", section:7 },
  { id:"0684", word:"working-class", phonetic:"ˈwɜːrkɪŋklɑːs", pos:"形容詞", meaning:"労働者階級の", note:"", section:7 },
  { id:"0685", word:"corrupt", phonetic:"kəˈrʌpt", pos:"形容詞", meaning:"汚職の、腐敗した", note:"corruption 名 腐敗", section:7 },
  { id:"0686", word:"drastic", phonetic:"ˈdræstɪk", pos:"形容詞", meaning:"思いきった、抜本的な", note:"drastically 副 大幅に", section:7 },
  { id:"0687", word:"lucrative", phonetic:"ˈluːkrətɪv", pos:"形容詞", meaning:"もうかる", note:"≒ profitable", section:7 },
  { id:"0688", word:"adequate", phonetic:"ˈædɪkwɪt", pos:"形容詞", meaning:"十分な、適切な", note:"adequacy 名 適切さ", section:7 },
  { id:"0689", word:"scarce", phonetic:"skeərs", pos:"形容詞", meaning:"乏しい、少ない", note:"scarcity 名 不足; scarcely 副 ほとんど〜ない", section:7 },
  { id:"0690", word:"distinct", phonetic:"dɪˈstɪŋkt", pos:"形容詞", meaning:"はっきりわかる、明確な", note:"distinctly 副 はっきりと", section:7 },
  { id:"0691", word:"eligible", phonetic:"ˈelɪdʒɪbl", pos:"形容詞", meaning:"（規則などによって）資格を持つ", note:"eligibility 名 適格性", section:7 },
  { id:"0692", word:"pedestrian", phonetic:"pɪˈdestriən", pos:"形容詞", meaning:"徒歩の、単調な", note:"名 歩行者; pedestrian mall 歩行者専用地区", section:7 },
  { id:"0693", word:"exclusive", phonetic:"ɪkˈskluːsɪv", pos:"形容詞", meaning:"排他的な、専用の", note:"exclusively 副 もっぱら", section:7 },
  { id:"0694", word:"notable", phonetic:"ˈnoʊtəbl", pos:"形容詞", meaning:"目立った", note:"notably 副 顕著に", section:7 },
  { id:"0695", word:"confidential", phonetic:"ˌkɒnfɪˈdenʃl", pos:"形容詞", meaning:"秘密の、機密の", note:"confidential document 機密文書", section:7 },
  { id:"0696", word:"overdue", phonetic:"ˌoʊvərˈdjuː", pos:"形容詞", meaning:"期限が過ぎた、変更が遅れ過ぎた", note:"overdue bill 支払期限を過ぎた請求書", section:7 },
  { id:"0697", word:"respiratory", phonetic:"rɪˈspɪrətɔːri", pos:"形容詞", meaning:"呼吸器に関する", note:"respiratory system 呼吸器系", section:7 },
  { id:"0698", word:"edible", phonetic:"ˈedɪbl", pos:"形容詞", meaning:"食用に適した", note:"edible fish 食用魚", section:7 },
  // --- 副詞 ---
  { id:"0699", word:"supposedly", phonetic:"səˈpoʊzɪdli", pos:"副詞", meaning:"一般にそう言われているところでは、推定では", note:"≒ apparently", section:7 },
  { id:"0700", word:"thoroughly", phonetic:"ˈθʌrəli", pos:"副詞", meaning:"徹底的に、完全に", note:"≒ meticulously, completely", section:7 },
];

// セクションの定義
const SECTIONS_DEF = [
  { key:"all", label:"全部（0001〜0700）全700語", range:[1,700] },
  { key:"s1",  label:"Section 1（0001〜0100）", range:[1,100] },
  { key:"s2",  label:"Section 2（0101〜0200）", range:[101,200] },
  { key:"s3",  label:"Section 3（0201〜0300）", range:[201,300] },
  { key:"s4",  label:"Section 4（0301〜0400）", range:[301,400] },
  { key:"s5",  label:"Section 5（0401〜0500）", range:[401,500] },
  { key:"s6",  label:"Section 6（0501〜0600）", range:[501,600] },
  { key:"s7",  label:"Section 7（0601〜0700）", range:[601,700] },
];
